/* Generated by           cobc 3.2.0 */
/* Generated from         atr.cob */
/* Generated at           abr 25 2026 16:10:32 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o atr atr.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"atr.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 16:10:32"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		161032

/* Global variables */
#include "atr.c.h"

/* Function prototypes */

static int		ATR ();
static int		ATR_ (const int);
static void		ATR_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (ATR ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'ATR' */

/* ENTRY 'ATR' */

static int
ATR ()
{
  return ATR_ (0);
}

static int
ATR_ (const int entry)
{
  /* Program local variables */
  #include "atr.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 49        : Entry     ATR                     : atr.cob */
  l_2:;
#line 49 "atr.cob"
  ENTRY_ATR:	cob_nop ();
#line 109 "atr.c"

  /* Line: 49        : Paragraph MAIN                    : atr.cob */
#line 49 "atr.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "atr.c"

  /* Line: 50        : DISPLAY            : atr.cob */
#line 50 "atr.cob"
  cob_nop ();
#line 119 "atr.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 51        : ACCEPT             : atr.cob */
#line 51 "atr.cob"
  cob_nop ();
#line 125 "atr.c"
  cob_accept_command_line (&f_27);

  /* Line: 52        : IF                 : atr.cob */
#line 52 "atr.cob"
  cob_nop ();
#line 131 "atr.c"
  if (((int)memcmp (b_27, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 53        : MOVE               : atr.cob */
#line 53 "atr.cob"
    cob_nop ();
#line 138 "atr.c"
    cob_move ((cob_field *)&c_4, &f_27);
  }

  /* Line: 55        : DISPLAY            : atr.cob */
#line 55 "atr.cob"
  cob_nop ();
#line 145 "atr.c"
  cob_display (0, 1, 2, &c_5, &f_27);

  /* Line: 7         : OPEN               : WS-PRICES-LOAD-HLC.cpy */
#line 7 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 151 "atr.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_24);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_1;
    l_11:
    frame_ptr--;
  }

  /* Line: 8         : IF                 : WS-PRICES-LOAD-HLC.cpy */
#line 8 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 169 "atr.c"
  if (!((int)memcmp (b_24, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 9         : PERFORM            : WS-PRICES-LOAD-HLC.cpy */
#line 9 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 176 "atr.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_9;
    l_12:
    frame_ptr--;
  }

  /* Line: 11        : IF                 : WS-PRICES-LOAD-HLC.cpy */
#line 11 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 191 "atr.c"
  if (((int)cob_cmpswp_s16 (b_39, 0LL) != 0))
  {

    /* Line: 12        : EXIT PARAGRAPH     : WS-PRICES-LOAD-HLC.cpy */
#line 12 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 198 "atr.c"
    goto l_5;
  }

  /* Line: 14        : MOVE               : WS-PRICES-LOAD-HLC.cpy */
#line 14 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 205 "atr.c"
  cob_move ((cob_field *)&c_6, &f_34);

  /* Line: 15        : PERFORM            : WS-PRICES-LOAD-HLC.cpy */
#line 15 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 211 "atr.c"
  for (;;)
  {
    /* Line: 15        : UNTIL              : WS-PRICES-LOAD-HLC.cpy */
#line 15 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 217 "atr.c"
    if (((int)memcmp (b_24, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 16        : READ               : WS-PRICES-LOAD-HLC.cpy */
#line 16 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 224 "atr.c"
    cob_read_next (h_FD_PRICES_FILE, &f_24, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 18        : SET                : WS-PRICES-LOAD-HLC.cpy */
#line 18 "WS-PRICES-LOAD-HLC.cpy"
        cob_nop ();
#line 234 "atr.c"
        memcpy (b_24, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_13;
        goto l_1;
        l_13:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_23, b_23, 32);

      /* Line: 20        : ADD                : WS-PRICES-LOAD-HLC.cpy */
#line 20 "WS-PRICES-LOAD-HLC.cpy"
      cob_nop ();
#line 257 "atr.c"
      cob_add (&f_34, (cob_field *)&c_1, 4);

      /* Line: 21        : COMPUTE            : WS-PRICES-LOAD-HLC.cpy */
#line 21 "WS-PRICES-LOAD-HLC.cpy"
      cob_nop ();
#line 263 "atr.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_5), 1);

      /* Line: 23        : COMPUTE            : WS-PRICES-LOAD-HLC.cpy */
#line 23 "WS-PRICES-LOAD-HLC.cpy"
      cob_nop ();
#line 270 "atr.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_20));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_5), 1);

      /* Line: 25        : COMPUTE            : WS-PRICES-LOAD-HLC.cpy */
#line 25 "WS-PRICES-LOAD-HLC.cpy"
      cob_nop ();
#line 277 "atr.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_22));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 8 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_5), 1);
    }
  }

  /* Line: 29        : DISPLAY            : WS-PRICES-LOAD-HLC.cpy */
#line 29 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 286 "atr.c"
  cob_display (0, 1, 3, &c_7, &f_34, &c_8);

  /* Line: 31        : CLOSE              : WS-PRICES-LOAD-HLC.cpy */
#line 31 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 292 "atr.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_1;
    l_14:
    frame_ptr--;
  }

  /* Line: 32        : IF                 : WS-PRICES-LOAD-HLC.cpy */
#line 32 "WS-PRICES-LOAD-HLC.cpy"
  cob_nop ();
#line 310 "atr.c"
  if (((int)cob_cmpswp_u16 (b_34, 0LL) == 0))
  {

    /* Line: 33        : MOVE               : WS-PRICES-LOAD-HLC.cpy */
#line 33 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 317 "atr.c"
    cob_move ((cob_field *)&c_9, &f_40);

    /* Line: 34        : DISPLAY            : WS-PRICES-LOAD-HLC.cpy */
#line 34 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 323 "atr.c"
    cob_display (0, 1, 1, &f_40);

    /* Line: 35        : MOVE               : WS-PRICES-LOAD-HLC.cpy */
#line 35 "WS-PRICES-LOAD-HLC.cpy"
    cob_nop ();
#line 329 "atr.c"
    cob_move ((cob_field *)&c_1, &f_39);
  }

  /* Line: 58        : IF                 : atr.cob */
#line 58 "atr.cob"
  cob_nop ();
#line 336 "atr.c"
  if (((int)cob_cmpswp_s16 (b_39, 0LL) != 0))
  {

    /* Line: 59        : PERFORM            : atr.cob */
#line 59 "atr.cob"
    cob_nop ();
#line 343 "atr.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_8;
    l_15:
    frame_ptr--;

    /* Line: 60        : STOP RUN           : atr.cob */
#line 60 "atr.cob"
    cob_nop ();
#line 357 "atr.c"
    cob_stop_run (b_2);
  }

  /* Line: 62        : DISPLAY            : atr.cob */
#line 62 "atr.cob"
  cob_nop ();
#line 364 "atr.c"
  cob_display (0, 1, 4, &c_10, &f_34, &c_11, &f_36);

  /* Line: 64        : PERFORM            : atr.cob */
#line 64 "atr.cob"
  cob_nop ();
#line 370 "atr.c"
  /* PERFORM 3100-CALCULAR-TRUE-RANGE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_6;
  l_16:
  frame_ptr--;

  /* Line: 65        : PERFORM            : atr.cob */
#line 65 "atr.cob"
  cob_nop ();
#line 384 "atr.c"
  /* PERFORM 3200-CALCULAR-ATR-FINAL */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_7;
  l_17:
  frame_ptr--;

  /* Line: 66        : DISPLAY            : atr.cob */
#line 66 "atr.cob"
  cob_nop ();
#line 398 "atr.c"
  cob_display (0, 1, 2, &c_12, &c_13);

  /* Line: 68        : PERFORM            : atr.cob */
#line 68 "atr.cob"
  cob_nop ();
#line 404 "atr.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_8;
  l_18:
  frame_ptr--;

  /* Line: 69        : STOP RUN           : atr.cob */
#line 69 "atr.cob"
  cob_nop ();
#line 418 "atr.c"
  cob_stop_run (b_2);

  /* Implicit EXIT label */
  l_5:;

  /* Line: 71        : Paragraph 3100-CALCULAR-TRUE-RANGE: atr.cob */
  l_6:;
#line 71 "atr.cob"
  PARAGRAPH_3100__CALCULAR__TRUE__RANGE_l_6:	cob_nop ();
#line 428 "atr.c"

  /* Line: 72        : MOVE               : atr.cob */
#line 72 "atr.cob"
  cob_nop ();
#line 433 "atr.c"
  memcpy (b_41, b_28 + 8, 4);

  /* Line: 73        : MOVE               : atr.cob */
#line 73 "atr.cob"
  cob_nop ();
#line 439 "atr.c"
  cob_move ((cob_field *)&c_6, &f_34);

  /* Line: 74        : PERFORM            : atr.cob */
#line 74 "atr.cob"
  cob_nop ();
#line 445 "atr.c"
  cob_move ((cob_field *)&c_2, &f_35);
  for (;;)
  {
    /* Line: 75        : UNTIL              : atr.cob */
#line 75 "atr.cob"
    cob_nop ();
#line 452 "atr.c"
    if (((int)(
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_35)))),
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_36))),
    cob_decimal_add (d_1, dc_1),
    cob_decimal_cmp (d_0, d_1)) > 0))
      break;

    /* Line: 76        : ADD                : atr.cob */
#line 76 "atr.cob"
    cob_nop ();
#line 463 "atr.c"
    cob_add (&f_34, (cob_field *)&c_1, 4);

    /* Line: 77        : COMPUTE            : atr.cob */
#line 77 "atr.cob"
    cob_nop ();
#line 469 "atr.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5));
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_42, 0);

    /* Line: 79        : COMPUTE            : atr.cob */
#line 79 "atr.cob"
    cob_nop ();
#line 478 "atr.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5));
    cob_decimal_set_field (d_1, &f_41);
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_43, 0);

    /* Line: 81        : COMPUTE            : atr.cob */
#line 81 "atr.cob"
    cob_nop ();
#line 487 "atr.c"
    cob_decimal_set_field (d_0, &f_41);
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_44, 0);

    /* Line: 83        : MOVE               : atr.cob */
#line 83 "atr.cob"
    cob_nop ();
#line 496 "atr.c"
    memcpy (b_45, b_42, 4);

    /* Line: 84        : IF                 : atr.cob */
#line 84 "atr.cob"
    cob_nop ();
#line 502 "atr.c"
    if (((int)cob_bcd_cmp (&f_43, &f_45) > 0))
    {

      /* Line: 85        : MOVE               : atr.cob */
#line 85 "atr.cob"
      cob_nop ();
#line 509 "atr.c"
      memcpy (b_45, b_43, 4);
    }

    /* Line: 87        : IF                 : atr.cob */
#line 87 "atr.cob"
    cob_nop ();
#line 516 "atr.c"
    if (((int)cob_bcd_cmp (&f_44, &f_45) > 0))
    {

      /* Line: 88        : MOVE               : atr.cob */
#line 88 "atr.cob"
      cob_nop ();
#line 523 "atr.c"
      memcpy (b_45, b_44, 4);
    }

    /* Line: 90        : MOVE               : atr.cob */
#line 90 "atr.cob"
    cob_nop ();
#line 530 "atr.c"
    memcpy (b_46 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), b_45, 4);

    /* Line: 91        : MOVE               : atr.cob */
#line 91 "atr.cob"
    cob_nop ();
#line 536 "atr.c"
    memcpy (b_41, b_28 + 8 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), 4);
    /* Line: 74        : VARYING            : atr.cob */
#line 74 "atr.cob"
    cob_nop ();
#line 541 "atr.c"
    cob_addswp_u16 (b_35, 1);
  }

  /* Line: 93        : EXIT               : atr.cob */
#line 93 "atr.cob"
  cob_nop ();
#line 548 "atr.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 95        : Paragraph 3200-CALCULAR-ATR-FINAL : atr.cob */
  l_7:;
#line 95 "atr.cob"
  PARAGRAPH_3200__CALCULAR__ATR__FINAL_l_7:	cob_nop ();
#line 558 "atr.c"

  /* Line: 96        : MOVE               : atr.cob */
#line 96 "atr.cob"
  cob_nop ();
#line 563 "atr.c"
  cob_set_packed_zero (&f_37);

  /* Line: 97        : PERFORM            : atr.cob */
#line 97 "atr.cob"
  cob_nop ();
#line 569 "atr.c"
  cob_move ((cob_field *)&c_1, &f_35);
  for (;;)
  {
    /* Line: 98        : UNTIL              : atr.cob */
#line 98 "atr.cob"
    cob_nop ();
#line 576 "atr.c"
    if (((int)cob_cmpswp_u16 (b_35, (*(cob_u8_ptr) (b_36))) > 0))
      break;

    /* Line: 99        : ADD                : atr.cob */
#line 99 "atr.cob"
    cob_nop ();
#line 583 "atr.c"
    cob_add (&f_37, COB_SET_FLD (f0, 4, b_46 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5), 0);
    /* Line: 97        : VARYING            : atr.cob */
#line 97 "atr.cob"
    cob_nop ();
#line 588 "atr.c"
    cob_addswp_u16 (b_35, 1);
  }

  /* Line: 101       : COMPUTE            : atr.cob */
#line 101 "atr.cob"
  cob_nop ();
#line 595 "atr.c"
  cob_decimal_set_field (d_0, &f_37);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_36)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_37, 1);

  /* Line: 102       : COMPUTE            : atr.cob */
#line 102 "atr.cob"
  cob_nop ();
#line 604 "atr.c"
  cob_decimal_set_ullint (d_0, (*(cob_u8_ptr) (b_36)));
  cob_decimal_add (d_0, dc_2);
  cob_decimal_get_field (d_0, &f_38, 4);

  /* Line: 103       : PERFORM            : atr.cob */
#line 103 "atr.cob"
  cob_nop ();
#line 612 "atr.c"
  memcpy (b_35, b_38, 2);
  for (;;)
  {
    /* Line: 104       : UNTIL              : atr.cob */
#line 104 "atr.cob"
    cob_nop ();
#line 619 "atr.c"
    if (((int)cob_cmpswp_u16 (b_35, ((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) > 0))
      break;

    /* Line: 105       : COMPUTE            : atr.cob */
#line 105 "atr.cob"
    cob_nop ();
#line 626 "atr.c"
    cob_decimal_set_field (d_0, &f_37);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_36)));
    cob_decimal_sub (d_1, dc_1);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_46 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_5));
    cob_decimal_add (d_0, d_1);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_36)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_37, 1);

    /* Line: 108       : DISPLAY            : atr.cob */
#line 108 "atr.cob"
    cob_nop ();
#line 640 "atr.c"
    cob_display (0, 1, 1, &f_37);
    /* Line: 103       : VARYING            : atr.cob */
#line 103 "atr.cob"
    cob_nop ();
#line 645 "atr.c"
    cob_addswp_u16 (b_35, 1);
  }

  /* Line: 110       : EXIT               : atr.cob */
#line 110 "atr.cob"
  cob_nop ();
#line 652 "atr.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 112       : Paragraph 9000-FINALIZAR          : atr.cob */
  l_8:;
#line 112 "atr.cob"
  PARAGRAPH_9000__FINALIZAR_l_8:	cob_nop ();
#line 662 "atr.c"

  /* Line: 113       : CLOSE              : atr.cob */
#line 113 "atr.cob"
  cob_nop ();
#line 667 "atr.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 114       : EXIT               : atr.cob */
#line 114 "atr.cob"
  cob_nop ();
#line 685 "atr.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 116       : Paragraph 9999-MANEJAR-ERROR-FS   : atr.cob */
  l_9:;
#line 116 "atr.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_9:	cob_nop ();
#line 695 "atr.c"

  /* Line: 117       : EVALUATE           : atr.cob */
#line 117 "atr.cob"
  cob_nop ();
#line 700 "atr.c"

  /* Line: 118       : WHEN               : atr.cob */
#line 118 "atr.cob"
  cob_nop ();
#line 705 "atr.c"

  if (((int)memcmp (b_24, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 119       : MOVE               : atr.cob */
#line 119 "atr.cob"
    cob_nop ();
#line 713 "atr.c"
    cob_move ((cob_field *)&c_14, &f_40);
    goto l_10;
  }

  /* Line: 120       : WHEN               : atr.cob */
#line 120 "atr.cob"
  cob_nop ();
#line 721 "atr.c"

  if (((int)memcmp (b_24, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 121       : MOVE               : atr.cob */
#line 121 "atr.cob"
    cob_nop ();
#line 729 "atr.c"
    cob_move ((cob_field *)&c_15, &f_40);
    goto l_10;
  }

  /* WHEN OTHER */

  /* Line: 123       : STRING             : atr.cob */
#line 123 "atr.cob"
  cob_nop ();
#line 739 "atr.c"
  cob_string_init (&f_40, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_16);
  cob_string_append (&f_24);
  cob_string_finish ();

  /* End EVALUATE */
  l_10:;

  /* Line: 126       : DISPLAY            : atr.cob */
#line 126 "atr.cob"
  cob_nop ();
#line 752 "atr.c"
  cob_display (0, 1, 1, &f_40);

  /* Line: 127       : MOVE               : atr.cob */
#line 127 "atr.cob"
  cob_nop ();
#line 758 "atr.c"
  cob_move ((cob_field *)&c_1, &f_39);

  /* Line: 128       : CLOSE              : atr.cob */
#line 128 "atr.cob"
  cob_nop ();
#line 764 "atr.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_1;
    l_20:
    frame_ptr--;
  }

  /* Line: 129       : EXIT               : atr.cob */
#line 129 "atr.cob"
  cob_nop ();
#line 782 "atr.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : atr.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  ATR_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 26 "atr.cob"
  cob_nop ();
#line 853 "atr.c"
  b_30 = 1;

  /* initialize field WS-TR-IDX */
#line 45 "atr.cob"
  cob_nop ();
#line 859 "atr.c"
  b_48 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 20 "atr.cob"
  cob_nop ();
#line 865 "atr.c"
  memset (b_24, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 23 "atr.cob"
  cob_nop ();
#line 871 "atr.c"
  memset (b_27, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-HIGH-COMP3 */
#line 27 "atr.cob"
    cob_nop ();
#line 879 "atr.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28, &a_5));
    /* initialize field WS-LOW-COMP3 */
#line 28 "atr.cob"
    cob_nop ();
#line 884 "atr.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28 + 4, &a_5));
    /* initialize field WS-CLOSE-COMP3 */
#line 29 "atr.cob"
    cob_nop ();
#line 889 "atr.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28 + 8, &a_5));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_28;
      memcpy (b_ptr +     12, b_ptr,     12);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +     24, b_ptr,     24);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     48, b_ptr,     48);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     96, b_ptr,     96);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +    192, b_ptr,    192);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    384, b_ptr,    384);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    768, b_ptr,    768);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +   1536, b_ptr,   1536);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   3072, b_ptr,   3072);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   6144, b_ptr,   5856);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 30 "atr.cob"
  cob_nop ();
#line 910 "atr.c"
  cob_move ((cob_field *)&c_6, &f_34);

  /* initialize field WS-I */
#line 31 "atr.cob"
  cob_nop ();
#line 916 "atr.c"
  memset (b_35, 0x0, 2);

  /* initialize field WS-PERIOD */
#line 32 "atr.cob"
  cob_nop ();
#line 922 "atr.c"
  cob_move ((cob_field *)&c_17, &f_36);

  /* initialize field WS-ATR */
#line 33 "atr.cob"
  cob_nop ();
#line 928 "atr.c"
  cob_set_packed_zero (&f_37);

  /* initialize field WS-START-IDX */
#line 34 "atr.cob"
  cob_nop ();
#line 934 "atr.c"
  memset (b_38, 0x0, 2);

  /* initialize field WS-EXIT-CODE */
#line 35 "atr.cob"
  cob_nop ();
#line 940 "atr.c"
  cob_move ((cob_field *)&c_6, &f_39);

  /* initialize field WS-ERROR-MSG */
#line 36 "atr.cob"
  cob_nop ();
#line 946 "atr.c"
  memset (b_40, (unsigned char)' ', 100);

  /* initialize field WS-PREV-CLOSE */
#line 37 "atr.cob"
  cob_nop ();
#line 952 "atr.c"
  cob_set_packed_zero (&f_41);

  /* initialize field WS-DIFF1 */
#line 38 "atr.cob"
  cob_nop ();
#line 958 "atr.c"
  cob_set_packed_zero (&f_42);

  /* initialize field WS-DIFF2 */
#line 39 "atr.cob"
  cob_nop ();
#line 964 "atr.c"
  cob_set_packed_zero (&f_43);

  /* initialize field WS-DIFF3 */
#line 40 "atr.cob"
  cob_nop ();
#line 970 "atr.c"
  cob_set_packed_zero (&f_44);

  /* initialize field WS-MAX-DIFF */
#line 41 "atr.cob"
  cob_nop ();
#line 976 "atr.c"
  cob_set_packed_zero (&f_45);

  /* initialize WS-TR-ENTRY: init first record */
  {
    /* initialize field WS-TR-VAL */
#line 46 "atr.cob"
    cob_nop ();
#line 984 "atr.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_46, &a_5));
    /* initialize WS-TR-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_46;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-TR-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-TR-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-TR-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-TR-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-TR-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-TR-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-TR-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-TR-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-TR-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-TR-ENTRY:   513 thru 1000 */
    }
  }


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_27;
  h_FD_PRICES_FILE->record = &f_23;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 32;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'ATR' */

/* Initialize module structure for ATR */
static void ATR_module_init (cob_module *module)
{
  module->module_name = "ATR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())ATR;
  module->module_cancel.funcptr = (void *(*)())ATR_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

