/* Generated by           cobc 3.2.0 */
/* Generated from         bollinger.cob */
/* Generated at           abr 25 2026 15:54:22 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o bollinger bollinger.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"bollinger.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:54:22"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		155422

/* Global variables */
#include "bollinger.c.h"

/* Function prototypes */

static int		BOLLINGER ();
static int		BOLLINGER_ (const int);
static void		BOLLINGER_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (BOLLINGER ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'BOLLINGER' */

/* ENTRY 'BOLLINGER' */

static int
BOLLINGER ()
{
  return BOLLINGER_ (0);
}

static int
BOLLINGER_ (const int entry)
{
  /* Program local variables */
  #include "bollinger.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (3, &d_0, &d_1, &d_2);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 41        : Entry     BOLLINGER               : bollinger.cob */
  l_2:;
#line 41 "bollinger.cob"
  ENTRY_BOLLINGER:	cob_nop ();
#line 109 "bollinger.c"

  /* Line: 41        : Paragraph MAIN                    : bollinger.cob */
#line 41 "bollinger.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "bollinger.c"

  /* Line: 42        : DISPLAY            : bollinger.cob */
#line 42 "bollinger.cob"
  cob_nop ();
#line 119 "bollinger.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 43        : ACCEPT             : bollinger.cob */
#line 43 "bollinger.cob"
  cob_nop ();
#line 125 "bollinger.c"
  cob_accept_command_line (&f_23);

  /* Line: 44        : IF                 : bollinger.cob */
#line 44 "bollinger.cob"
  cob_nop ();
#line 131 "bollinger.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 45        : MOVE               : bollinger.cob */
#line 45 "bollinger.cob"
    cob_nop ();
#line 138 "bollinger.c"
    cob_move ((cob_field *)&c_3, &f_23);
  }

  /* Line: 47        : DISPLAY            : bollinger.cob */
#line 47 "bollinger.cob"
  cob_nop ();
#line 145 "bollinger.c"
  cob_display (0, 1, 2, &c_4, &f_23);

  /* Line: 7         : OPEN               : WS-PRICES-LOAD.cpy */
#line 7 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 151 "bollinger.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_1;
    l_10:
    frame_ptr--;
  }

  /* Line: 8         : IF                 : WS-PRICES-LOAD.cpy */
#line 8 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 169 "bollinger.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 9         : PERFORM            : WS-PRICES-LOAD.cpy */
#line 9 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 176 "bollinger.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_8;
    l_11:
    frame_ptr--;
  }

  /* Line: 11        : IF                 : WS-PRICES-LOAD.cpy */
#line 11 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 191 "bollinger.c"
  if (((int)cob_cmpswp_s16 (b_41, 0LL) != 0))
  {

    /* Line: 12        : EXIT PARAGRAPH     : WS-PRICES-LOAD.cpy */
#line 12 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 198 "bollinger.c"
    goto l_5;
  }

  /* Line: 14        : MOVE               : WS-PRICES-LOAD.cpy */
#line 14 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 205 "bollinger.c"
  cob_move ((cob_field *)&c_5, &f_28);

  /* Line: 15        : PERFORM            : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 211 "bollinger.c"
  for (;;)
  {
    /* Line: 15        : UNTIL              : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 217 "bollinger.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 16        : READ               : WS-PRICES-LOAD.cpy */
#line 16 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 224 "bollinger.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 18        : SET                : WS-PRICES-LOAD.cpy */
#line 18 "WS-PRICES-LOAD.cpy"
        cob_nop ();
#line 234 "bollinger.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_12;
        goto l_1;
        l_12:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 20        : ADD                : WS-PRICES-LOAD.cpy */
#line 20 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 257 "bollinger.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 21        : COMPUTE            : WS-PRICES-LOAD.cpy */
#line 21 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 263 "bollinger.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_5), 1);
    }
  }

  /* Line: 25        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 25 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 272 "bollinger.c"
  cob_display (0, 1, 3, &c_6, &f_28, &c_7);

  /* Line: 27        : CLOSE              : WS-PRICES-LOAD.cpy */
#line 27 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 278 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_13;
    goto l_1;
    l_13:
    frame_ptr--;
  }

  /* Line: 28        : IF                 : WS-PRICES-LOAD.cpy */
#line 28 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 296 "bollinger.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 29        : MOVE               : WS-PRICES-LOAD.cpy */
#line 29 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 303 "bollinger.c"
    cob_move ((cob_field *)&c_8, &f_42);

    /* Line: 30        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 30 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 309 "bollinger.c"
    cob_display (0, 1, 1, &f_42);

    /* Line: 31        : MOVE               : WS-PRICES-LOAD.cpy */
#line 31 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 315 "bollinger.c"
    cob_move ((cob_field *)&c_1, &f_41);
  }

  /* Line: 50        : IF                 : bollinger.cob */
#line 50 "bollinger.cob"
  cob_nop ();
#line 322 "bollinger.c"
  if (((int)cob_cmpswp_s16 (b_41, 0LL) != 0))
  {

    /* Line: 51        : PERFORM            : bollinger.cob */
#line 51 "bollinger.cob"
    cob_nop ();
#line 329 "bollinger.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_7;
    l_14:
    frame_ptr--;

    /* Line: 52        : STOP RUN           : bollinger.cob */
#line 52 "bollinger.cob"
    cob_nop ();
#line 343 "bollinger.c"
    cob_stop_run (b_2);
  }

  /* Line: 54        : DISPLAY            : bollinger.cob */
#line 54 "bollinger.cob"
  cob_nop ();
#line 350 "bollinger.c"
  cob_display (0, 1, 4, &c_9, &f_28, &c_10, &f_31);

  /* Line: 56        : PERFORM            : bollinger.cob */
#line 56 "bollinger.cob"
  cob_nop ();
#line 356 "bollinger.c"
  /* PERFORM 3000-CALCULAR-BOLLINGER */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_15;
  goto l_6;
  l_15:
  frame_ptr--;

  /* Line: 57        : DISPLAY            : bollinger.cob */
#line 57 "bollinger.cob"
  cob_nop ();
#line 370 "bollinger.c"
  cob_display (0, 1, 2, &c_11, &c_12);

  /* Line: 59        : PERFORM            : bollinger.cob */
#line 59 "bollinger.cob"
  cob_nop ();
#line 376 "bollinger.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_7;
  l_16:
  frame_ptr--;

  /* Line: 60        : STOP RUN           : bollinger.cob */
#line 60 "bollinger.cob"
  cob_nop ();
#line 390 "bollinger.c"
  cob_stop_run (b_2);

  /* Implicit EXIT label */
  l_5:;

  /* Line: 62        : Paragraph 3000-CALCULAR-BOLLINGER : bollinger.cob */
  l_6:;
#line 62 "bollinger.cob"
  PARAGRAPH_3000__CALCULAR__BOLLINGER_l_6:	cob_nop ();
#line 400 "bollinger.c"

  /* Line: 63        : PERFORM            : bollinger.cob */
#line 63 "bollinger.cob"
  cob_nop ();
#line 405 "bollinger.c"
  cob_move (&f_31, &f_29);
  for (;;)
  {
    /* Line: 64        : UNTIL              : bollinger.cob */
#line 64 "bollinger.cob"
    cob_nop ();
#line 412 "bollinger.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) > 0))
      break;

    /* Line: 65        : MOVE               : bollinger.cob */
#line 65 "bollinger.cob"
    cob_nop ();
#line 419 "bollinger.c"
    cob_set_packed_zero (&f_33);

    /* Line: 66        : COMPUTE            : bollinger.cob */
#line 66 "bollinger.cob"
    cob_nop ();
#line 425 "bollinger.c"
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_29))));
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_32, 4);

    /* Line: 67        : PERFORM            : bollinger.cob */
#line 67 "bollinger.cob"
    cob_nop ();
#line 435 "bollinger.c"
    memcpy (b_30, b_32, 2);
    for (;;)
    {
      /* Line: 68        : UNTIL              : bollinger.cob */
#line 68 "bollinger.cob"
      cob_nop ();
#line 442 "bollinger.c"
      if (((int)cob_cmpswp_u16 (b_30, ((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) > 0))
        break;

      /* Line: 69        : ADD                : bollinger.cob */
#line 69 "bollinger.cob"
      cob_nop ();
#line 449 "bollinger.c"
      cob_add (&f_33, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_30)))) - 1), &a_5), 0);
      /* Line: 67        : VARYING            : bollinger.cob */
#line 67 "bollinger.cob"
      cob_nop ();
#line 454 "bollinger.c"
      cob_addswp_u16 (b_30, 1);
    }

    /* Line: 71        : COMPUTE            : bollinger.cob */
#line 71 "bollinger.cob"
    cob_nop ();
#line 461 "bollinger.c"
    cob_decimal_set_field (d_0, &f_33);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_34, 1);

    /* Line: 72        : MOVE               : bollinger.cob */
#line 72 "bollinger.cob"
    cob_nop ();
#line 470 "bollinger.c"
    cob_set_packed_zero (&f_35);

    /* Line: 73        : PERFORM            : bollinger.cob */
#line 73 "bollinger.cob"
    cob_nop ();
#line 476 "bollinger.c"
    memcpy (b_30, b_32, 2);
    for (;;)
    {
      /* Line: 74        : UNTIL              : bollinger.cob */
#line 74 "bollinger.cob"
      cob_nop ();
#line 483 "bollinger.c"
      if (((int)cob_cmpswp_u16 (b_30, ((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) > 0))
        break;

      /* Line: 75        : COMPUTE            : bollinger.cob */
#line 75 "bollinger.cob"
      cob_nop ();
#line 490 "bollinger.c"
      cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_30)))) - 1), &a_5));
      cob_decimal_set_field (d_1, &f_34);
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_39, 0);

      /* Line: 76        : COMPUTE            : bollinger.cob */
#line 76 "bollinger.cob"
      cob_nop ();
#line 499 "bollinger.c"
      cob_decimal_set_field (d_0, &f_39);
      cob_decimal_set_field (d_1, &f_39);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_get_field (d_0, &f_40, 1);

      /* Line: 77        : ADD                : bollinger.cob */
#line 77 "bollinger.cob"
      cob_nop ();
#line 508 "bollinger.c"
      cob_add (&f_35, &f_40, 0);
      /* Line: 73        : VARYING            : bollinger.cob */
#line 73 "bollinger.cob"
      cob_nop ();
#line 513 "bollinger.c"
      cob_addswp_u16 (b_30, 1);
    }

    /* Line: 79        : COMPUTE            : bollinger.cob */
#line 79 "bollinger.cob"
    cob_nop ();
#line 520 "bollinger.c"
    cob_decimal_set_field (d_0, &f_35);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_35, 1);

    /* Line: 80        : COMPUTE            : bollinger.cob */
#line 80 "bollinger.cob"
    cob_nop ();
#line 529 "bollinger.c"
    cob_decimal_set_field (d_0, cob_intr_sqrt (&f_35));
    cob_decimal_get_field (d_0, &f_36, 0);

    /* Line: 81        : COMPUTE            : bollinger.cob */
#line 81 "bollinger.cob"
    cob_nop ();
#line 536 "bollinger.c"
    cob_decimal_set_field (d_0, &f_34);
    cob_decimal_set_llint (d_1, 2LL);
    cob_decimal_set_field (d_2, &f_36);
    cob_decimal_mul (d_1, d_2);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_37, 1);

    /* Line: 82        : COMPUTE            : bollinger.cob */
#line 82 "bollinger.cob"
    cob_nop ();
#line 547 "bollinger.c"
    cob_decimal_set_field (d_0, &f_34);
    cob_decimal_set_llint (d_1, 2LL);
    cob_decimal_set_field (d_2, &f_36);
    cob_decimal_mul (d_1, d_2);
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_38, 1);

    /* Line: 83        : DISPLAY            : bollinger.cob */
#line 83 "bollinger.cob"
    cob_nop ();
#line 558 "bollinger.c"
    cob_display (0, 1, 5, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_5), &c_13, &f_37, &c_13, &f_38);
    /* Line: 63        : VARYING            : bollinger.cob */
#line 63 "bollinger.cob"
    cob_nop ();
#line 563 "bollinger.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 85        : EXIT               : bollinger.cob */
#line 85 "bollinger.cob"
  cob_nop ();
#line 570 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 87        : Paragraph 9000-FINALIZAR          : bollinger.cob */
  l_7:;
#line 87 "bollinger.cob"
  PARAGRAPH_9000__FINALIZAR_l_7:	cob_nop ();
#line 580 "bollinger.c"

  /* Line: 88        : CLOSE              : bollinger.cob */
#line 88 "bollinger.cob"
  cob_nop ();
#line 585 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }

  /* Line: 89        : EXIT               : bollinger.cob */
#line 89 "bollinger.cob"
  cob_nop ();
#line 603 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 91        : Paragraph 9999-MANEJAR-ERROR-FS   : bollinger.cob */
  l_8:;
#line 91 "bollinger.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_8:	cob_nop ();
#line 613 "bollinger.c"

  /* Line: 92        : EVALUATE           : bollinger.cob */
#line 92 "bollinger.cob"
  cob_nop ();
#line 618 "bollinger.c"

  /* Line: 93        : WHEN               : bollinger.cob */
#line 93 "bollinger.cob"
  cob_nop ();
#line 623 "bollinger.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 94        : MOVE               : bollinger.cob */
#line 94 "bollinger.cob"
    cob_nop ();
#line 631 "bollinger.c"
    cob_move ((cob_field *)&c_14, &f_42);
    goto l_9;
  }

  /* Line: 95        : WHEN               : bollinger.cob */
#line 95 "bollinger.cob"
  cob_nop ();
#line 639 "bollinger.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 96        : MOVE               : bollinger.cob */
#line 96 "bollinger.cob"
    cob_nop ();
#line 647 "bollinger.c"
    cob_move ((cob_field *)&c_15, &f_42);
    goto l_9;
  }

  /* WHEN OTHER */

  /* Line: 98        : STRING             : bollinger.cob */
#line 98 "bollinger.cob"
  cob_nop ();
#line 657 "bollinger.c"
  cob_string_init (&f_42, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_16);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_9:;

  /* Line: 101       : DISPLAY            : bollinger.cob */
#line 101 "bollinger.cob"
  cob_nop ();
#line 670 "bollinger.c"
  cob_display (0, 1, 1, &f_42);

  /* Line: 102       : MOVE               : bollinger.cob */
#line 102 "bollinger.cob"
  cob_nop ();
#line 676 "bollinger.c"
  cob_move ((cob_field *)&c_1, &f_41);

  /* Line: 103       : CLOSE              : bollinger.cob */
#line 103 "bollinger.cob"
  cob_nop ();
#line 682 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 104       : EXIT               : bollinger.cob */
#line 104 "bollinger.cob"
  cob_nop ();
#line 700 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : bollinger.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  BOLLINGER_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 23 "bollinger.cob"
  cob_nop ();
#line 771 "bollinger.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 17 "bollinger.cob"
  cob_nop ();
#line 777 "bollinger.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 20 "bollinger.cob"
  cob_nop ();
#line 783 "bollinger.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 24 "bollinger.cob"
    cob_nop ();
#line 791 "bollinger.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_5));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 25 "bollinger.cob"
  cob_nop ();
#line 812 "bollinger.c"
  cob_move ((cob_field *)&c_5, &f_28);

  /* initialize field WS-I */
#line 26 "bollinger.cob"
  cob_nop ();
#line 818 "bollinger.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-J */
#line 27 "bollinger.cob"
  cob_nop ();
#line 824 "bollinger.c"
  memset (b_30, 0x0, 2);

  /* initialize field WS-PERIOD */
#line 28 "bollinger.cob"
  cob_nop ();
#line 830 "bollinger.c"
  cob_move ((cob_field *)&c_17, &f_31);

  /* initialize field WS-START-IDX */
#line 29 "bollinger.cob"
  cob_nop ();
#line 836 "bollinger.c"
  memset (b_32, 0x0, 2);

  /* initialize field WS-SUM */
#line 30 "bollinger.cob"
  cob_nop ();
#line 842 "bollinger.c"
  cob_set_packed_zero (&f_33);

  /* initialize field WS-SMA */
#line 31 "bollinger.cob"
  cob_nop ();
#line 848 "bollinger.c"
  memset (b_34, (unsigned char)'0', 7);

  /* initialize field WS-VARIANCE */
#line 32 "bollinger.cob"
  cob_nop ();
#line 854 "bollinger.c"
  cob_set_packed_zero (&f_35);

  /* initialize field WS-STD-DEV */
#line 33 "bollinger.cob"
  cob_nop ();
#line 860 "bollinger.c"
  memset (b_36, (unsigned char)'0', 7);

  /* initialize field WS-UPPER */
#line 34 "bollinger.cob"
  cob_nop ();
#line 866 "bollinger.c"
  memset (b_37, (unsigned char)'0', 7);

  /* initialize field WS-LOWER */
#line 35 "bollinger.cob"
  cob_nop ();
#line 872 "bollinger.c"
  memset (b_38, (unsigned char)'0', 7);

  /* initialize field WS-DIFF */
#line 36 "bollinger.cob"
  cob_nop ();
#line 878 "bollinger.c"
  cob_set_packed_zero (&f_39);

  /* initialize field WS-DIFF-SQ */
#line 37 "bollinger.cob"
  cob_nop ();
#line 884 "bollinger.c"
  cob_set_packed_zero (&f_40);

  /* initialize field WS-EXIT-CODE */
#line 38 "bollinger.cob"
  cob_nop ();
#line 890 "bollinger.c"
  cob_move ((cob_field *)&c_5, &f_41);

  /* initialize field WS-ERROR-MSG */
#line 39 "bollinger.cob"
  cob_nop ();
#line 896 "bollinger.c"
  memset (b_42, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'BOLLINGER' */

/* Initialize module structure for BOLLINGER */
static void BOLLINGER_module_init (cob_module *module)
{
  module->module_name = "BOLLINGER";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())BOLLINGER;
  module->module_cancel.funcptr = (void *(*)())BOLLINGER_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

