/* Generated by           cobc 3.2.0 */
/* Generated from         bollinger.cob */
/* Generated at           abr 25 2026 15:24:06 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o bollinger bollinger.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"bollinger.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:24:06"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		152406

/* Global variables */
#include "bollinger.c.h"

/* Function prototypes */

static int		BOLLINGER ();
static int		BOLLINGER_ (const int);
static void		BOLLINGER_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (BOLLINGER ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'BOLLINGER' */

/* ENTRY 'BOLLINGER' */

static int
BOLLINGER ()
{
  return BOLLINGER_ (0);
}

static int
BOLLINGER_ (const int entry)
{
  /* Program local variables */
  #include "bollinger.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (3, &d_0, &d_1, &d_2);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 40        : Entry     BOLLINGER               : bollinger.cob */
  l_2:;
#line 40 "bollinger.cob"
  ENTRY_BOLLINGER:	cob_nop ();
#line 109 "bollinger.c"

  /* Line: 40        : Paragraph MAIN                    : bollinger.cob */
#line 40 "bollinger.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "bollinger.c"

  /* Line: 41        : DISPLAY            : bollinger.cob */
#line 41 "bollinger.cob"
  cob_nop ();
#line 119 "bollinger.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 42        : ACCEPT             : bollinger.cob */
#line 42 "bollinger.cob"
  cob_nop ();
#line 125 "bollinger.c"
  cob_accept_command_line (&f_23);

  /* Line: 43        : IF                 : bollinger.cob */
#line 43 "bollinger.cob"
  cob_nop ();
#line 131 "bollinger.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 44        : MOVE               : bollinger.cob */
#line 44 "bollinger.cob"
    cob_nop ();
#line 138 "bollinger.c"
    cob_move ((cob_field *)&c_3, &f_23);
  }

  /* Line: 46        : DISPLAY            : bollinger.cob */
#line 46 "bollinger.cob"
  cob_nop ();
#line 145 "bollinger.c"
  cob_display (0, 1, 2, &c_4, &f_23);

  /* Line: 48        : PERFORM            : bollinger.cob */
#line 48 "bollinger.cob"
  cob_nop ();
#line 151 "bollinger.c"
  /* PERFORM 2000-LEER-PRECIOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 49        : IF                 : bollinger.cob */
#line 49 "bollinger.cob"
  cob_nop ();
#line 165 "bollinger.c"
  if (((int)cob_cmpswp_s16 (b_41, 0LL) != 0))
  {

    /* Line: 50        : PERFORM            : bollinger.cob */
#line 50 "bollinger.cob"
    cob_nop ();
#line 172 "bollinger.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_8;
    l_12:
    frame_ptr--;

    /* Line: 51        : STOP RUN           : bollinger.cob */
#line 51 "bollinger.cob"
    cob_nop ();
#line 186 "bollinger.c"
    cob_stop_run (b_2);
  }

  /* Line: 53        : DISPLAY            : bollinger.cob */
#line 53 "bollinger.cob"
  cob_nop ();
#line 193 "bollinger.c"
  cob_display (0, 1, 4, &c_5, &f_28, &c_6, &f_31);

  /* Line: 55        : PERFORM            : bollinger.cob */
#line 55 "bollinger.cob"
  cob_nop ();
#line 199 "bollinger.c"
  /* PERFORM 3000-CALCULAR-BOLLINGER */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_7;
  l_13:
  frame_ptr--;

  /* Line: 56        : DISPLAY            : bollinger.cob */
#line 56 "bollinger.cob"
  cob_nop ();
#line 213 "bollinger.c"
  cob_display (0, 1, 2, &c_7, &c_8);

  /* Line: 58        : PERFORM            : bollinger.cob */
#line 58 "bollinger.cob"
  cob_nop ();
#line 219 "bollinger.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_8;
  l_14:
  frame_ptr--;

  /* Line: 59        : STOP RUN           : bollinger.cob */
#line 59 "bollinger.cob"
  cob_nop ();
#line 233 "bollinger.c"
  cob_stop_run (b_2);

  /* Line: 61        : Paragraph 2000-LEER-PRECIOS       : bollinger.cob */
  l_5:;
#line 61 "bollinger.cob"
  PARAGRAPH_2000__LEER__PRECIOS_l_5:	cob_nop ();
#line 240 "bollinger.c"

  /* Line: 62        : OPEN               : bollinger.cob */
#line 62 "bollinger.cob"
  cob_nop ();
#line 245 "bollinger.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_1;
    l_15:
    frame_ptr--;
  }

  /* Line: 63        : IF                 : bollinger.cob */
#line 63 "bollinger.cob"
  cob_nop ();
#line 263 "bollinger.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 64        : PERFORM            : bollinger.cob */
#line 64 "bollinger.cob"
    cob_nop ();
#line 270 "bollinger.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_9;
    l_16:
    frame_ptr--;
  }

  /* Line: 66        : IF                 : bollinger.cob */
#line 66 "bollinger.cob"
  cob_nop ();
#line 285 "bollinger.c"
  if (((int)cob_cmpswp_s16 (b_41, 0LL) != 0))
  {

    /* Line: 67        : EXIT PARAGRAPH     : bollinger.cob */
#line 67 "bollinger.cob"
    cob_nop ();
#line 292 "bollinger.c"
    goto l_6;
  }

  /* Line: 69        : MOVE               : bollinger.cob */
#line 69 "bollinger.cob"
  cob_nop ();
#line 299 "bollinger.c"
  cob_move ((cob_field *)&c_9, &f_28);

  /* Line: 70        : PERFORM            : bollinger.cob */
#line 70 "bollinger.cob"
  cob_nop ();
#line 305 "bollinger.c"
  for (;;)
  {
    /* Line: 70        : UNTIL              : bollinger.cob */
#line 70 "bollinger.cob"
    cob_nop ();
#line 311 "bollinger.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 71        : READ               : bollinger.cob */
#line 71 "bollinger.cob"
    cob_nop ();
#line 318 "bollinger.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 73        : SET                : bollinger.cob */
#line 73 "bollinger.cob"
        cob_nop ();
#line 328 "bollinger.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_17;
        goto l_1;
        l_17:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 75        : ADD                : bollinger.cob */
#line 75 "bollinger.cob"
      cob_nop ();
#line 351 "bollinger.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 76        : COMPUTE            : bollinger.cob */
#line 76 "bollinger.cob"
      cob_nop ();
#line 357 "bollinger.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_6), 1);
    }
  }

  /* Line: 80        : DISPLAY            : bollinger.cob */
#line 80 "bollinger.cob"
  cob_nop ();
#line 366 "bollinger.c"
  cob_display (0, 1, 3, &c_10, &f_28, &c_11);

  /* Line: 82        : CLOSE              : bollinger.cob */
#line 82 "bollinger.cob"
  cob_nop ();
#line 372 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 83        : IF                 : bollinger.cob */
#line 83 "bollinger.cob"
  cob_nop ();
#line 390 "bollinger.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 84        : MOVE               : bollinger.cob */
#line 84 "bollinger.cob"
    cob_nop ();
#line 397 "bollinger.c"
    cob_move ((cob_field *)&c_12, &f_42);

    /* Line: 85        : DISPLAY            : bollinger.cob */
#line 85 "bollinger.cob"
    cob_nop ();
#line 403 "bollinger.c"
    cob_display (0, 1, 1, &f_42);

    /* Line: 86        : MOVE               : bollinger.cob */
#line 86 "bollinger.cob"
    cob_nop ();
#line 409 "bollinger.c"
    cob_move ((cob_field *)&c_1, &f_41);
  }

  /* Line: 88        : EXIT               : bollinger.cob */
#line 88 "bollinger.cob"
  cob_nop ();
#line 416 "bollinger.c"

  /* Implicit EXIT label */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 90        : Paragraph 3000-CALCULAR-BOLLINGER : bollinger.cob */
  l_7:;
#line 90 "bollinger.cob"
  PARAGRAPH_3000__CALCULAR__BOLLINGER_l_7:	cob_nop ();
#line 429 "bollinger.c"

  /* Line: 91        : PERFORM            : bollinger.cob */
#line 91 "bollinger.cob"
  cob_nop ();
#line 434 "bollinger.c"
  cob_move (&f_31, &f_29);
  for (;;)
  {
    /* Line: 92        : UNTIL              : bollinger.cob */
#line 92 "bollinger.cob"
    cob_nop ();
#line 441 "bollinger.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) > 0))
      break;

    /* Line: 93        : MOVE               : bollinger.cob */
#line 93 "bollinger.cob"
    cob_nop ();
#line 448 "bollinger.c"
    cob_set_packed_zero (&f_33);

    /* Line: 94        : COMPUTE            : bollinger.cob */
#line 94 "bollinger.cob"
    cob_nop ();
#line 454 "bollinger.c"
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_29))));
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_32, 4);

    /* Line: 95        : PERFORM            : bollinger.cob */
#line 95 "bollinger.cob"
    cob_nop ();
#line 464 "bollinger.c"
    memcpy (b_30, b_32, 2);
    for (;;)
    {
      /* Line: 96        : UNTIL              : bollinger.cob */
#line 96 "bollinger.cob"
      cob_nop ();
#line 471 "bollinger.c"
      if (((int)cob_cmpswp_u16 (b_30, ((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) > 0))
        break;

      /* Line: 97        : ADD                : bollinger.cob */
#line 97 "bollinger.cob"
      cob_nop ();
#line 478 "bollinger.c"
      cob_add (&f_33, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_30)))) - 1), &a_6), 0);
      /* Line: 95        : VARYING            : bollinger.cob */
#line 95 "bollinger.cob"
      cob_nop ();
#line 483 "bollinger.c"
      cob_addswp_u16 (b_30, 1);
    }

    /* Line: 99        : COMPUTE            : bollinger.cob */
#line 99 "bollinger.cob"
    cob_nop ();
#line 490 "bollinger.c"
    cob_decimal_set_field (d_0, &f_33);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_34, 1);

    /* Line: 100       : MOVE               : bollinger.cob */
#line 100 "bollinger.cob"
    cob_nop ();
#line 499 "bollinger.c"
    cob_set_packed_zero (&f_35);

    /* Line: 101       : PERFORM            : bollinger.cob */
#line 101 "bollinger.cob"
    cob_nop ();
#line 505 "bollinger.c"
    memcpy (b_30, b_32, 2);
    for (;;)
    {
      /* Line: 102       : UNTIL              : bollinger.cob */
#line 102 "bollinger.cob"
      cob_nop ();
#line 512 "bollinger.c"
      if (((int)cob_cmpswp_u16 (b_30, ((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) > 0))
        break;

      /* Line: 103       : COMPUTE            : bollinger.cob */
#line 103 "bollinger.cob"
      cob_nop ();
#line 519 "bollinger.c"
      cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_30)))) - 1), &a_6));
      cob_decimal_set_field (d_1, &f_34);
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_39, 0);

      /* Line: 104       : COMPUTE            : bollinger.cob */
#line 104 "bollinger.cob"
      cob_nop ();
#line 528 "bollinger.c"
      cob_decimal_set_field (d_0, &f_39);
      cob_decimal_set_field (d_1, &f_39);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_get_field (d_0, &f_40, 1);

      /* Line: 105       : ADD                : bollinger.cob */
#line 105 "bollinger.cob"
      cob_nop ();
#line 537 "bollinger.c"
      cob_add (&f_35, &f_40, 0);
      /* Line: 101       : VARYING            : bollinger.cob */
#line 101 "bollinger.cob"
      cob_nop ();
#line 542 "bollinger.c"
      cob_addswp_u16 (b_30, 1);
    }

    /* Line: 107       : COMPUTE            : bollinger.cob */
#line 107 "bollinger.cob"
    cob_nop ();
#line 549 "bollinger.c"
    cob_decimal_set_field (d_0, &f_35);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_35, 1);

    /* Line: 108       : COMPUTE            : bollinger.cob */
#line 108 "bollinger.cob"
    cob_nop ();
#line 558 "bollinger.c"
    cob_decimal_set_field (d_0, cob_intr_sqrt (&f_35));
    cob_decimal_get_field (d_0, &f_36, 0);

    /* Line: 109       : COMPUTE            : bollinger.cob */
#line 109 "bollinger.cob"
    cob_nop ();
#line 565 "bollinger.c"
    cob_decimal_set_field (d_0, &f_34);
    cob_decimal_set_llint (d_1, 2LL);
    cob_decimal_set_field (d_2, &f_36);
    cob_decimal_mul (d_1, d_2);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_37, 1);

    /* Line: 110       : COMPUTE            : bollinger.cob */
#line 110 "bollinger.cob"
    cob_nop ();
#line 576 "bollinger.c"
    cob_decimal_set_field (d_0, &f_34);
    cob_decimal_set_llint (d_1, 2LL);
    cob_decimal_set_field (d_2, &f_36);
    cob_decimal_mul (d_1, d_2);
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_38, 1);

    /* Line: 111       : DISPLAY            : bollinger.cob */
#line 111 "bollinger.cob"
    cob_nop ();
#line 587 "bollinger.c"
    cob_display (0, 1, 5, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6), &c_13, &f_37, &c_13, &f_38);
    /* Line: 91        : VARYING            : bollinger.cob */
#line 91 "bollinger.cob"
    cob_nop ();
#line 592 "bollinger.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 113       : EXIT               : bollinger.cob */
#line 113 "bollinger.cob"
  cob_nop ();
#line 599 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 115       : Paragraph 9000-FINALIZAR          : bollinger.cob */
  l_8:;
#line 115 "bollinger.cob"
  PARAGRAPH_9000__FINALIZAR_l_8:	cob_nop ();
#line 609 "bollinger.c"

  /* Line: 116       : CLOSE              : bollinger.cob */
#line 116 "bollinger.cob"
  cob_nop ();
#line 614 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 117       : EXIT               : bollinger.cob */
#line 117 "bollinger.cob"
  cob_nop ();
#line 632 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 119       : Paragraph 9999-MANEJAR-ERROR-FS   : bollinger.cob */
  l_9:;
#line 119 "bollinger.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_9:	cob_nop ();
#line 642 "bollinger.c"

  /* Line: 120       : EVALUATE           : bollinger.cob */
#line 120 "bollinger.cob"
  cob_nop ();
#line 647 "bollinger.c"

  /* Line: 121       : WHEN               : bollinger.cob */
#line 121 "bollinger.cob"
  cob_nop ();
#line 652 "bollinger.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 122       : MOVE               : bollinger.cob */
#line 122 "bollinger.cob"
    cob_nop ();
#line 660 "bollinger.c"
    cob_move ((cob_field *)&c_14, &f_42);
    goto l_10;
  }

  /* Line: 123       : WHEN               : bollinger.cob */
#line 123 "bollinger.cob"
  cob_nop ();
#line 668 "bollinger.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 124       : MOVE               : bollinger.cob */
#line 124 "bollinger.cob"
    cob_nop ();
#line 676 "bollinger.c"
    cob_move ((cob_field *)&c_15, &f_42);
    goto l_10;
  }

  /* WHEN OTHER */

  /* Line: 126       : STRING             : bollinger.cob */
#line 126 "bollinger.cob"
  cob_nop ();
#line 686 "bollinger.c"
  cob_string_init (&f_42, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_16);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_10:;

  /* Line: 129       : DISPLAY            : bollinger.cob */
#line 129 "bollinger.cob"
  cob_nop ();
#line 699 "bollinger.c"
  cob_display (0, 1, 1, &f_42);

  /* Line: 130       : MOVE               : bollinger.cob */
#line 130 "bollinger.cob"
  cob_nop ();
#line 705 "bollinger.c"
  cob_move ((cob_field *)&c_1, &f_41);

  /* Line: 131       : CLOSE              : bollinger.cob */
#line 131 "bollinger.cob"
  cob_nop ();
#line 711 "bollinger.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_1;
    l_20:
    frame_ptr--;
  }

  /* Line: 132       : EXIT               : bollinger.cob */
#line 132 "bollinger.cob"
  cob_nop ();
#line 729 "bollinger.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : bollinger.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  BOLLINGER_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 22 "bollinger.cob"
  cob_nop ();
#line 800 "bollinger.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 16 "bollinger.cob"
  cob_nop ();
#line 806 "bollinger.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 19 "bollinger.cob"
  cob_nop ();
#line 812 "bollinger.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 23 "bollinger.cob"
    cob_nop ();
#line 820 "bollinger.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_6));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 24 "bollinger.cob"
  cob_nop ();
#line 841 "bollinger.c"
  cob_move ((cob_field *)&c_9, &f_28);

  /* initialize field WS-I */
#line 25 "bollinger.cob"
  cob_nop ();
#line 847 "bollinger.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-J */
#line 26 "bollinger.cob"
  cob_nop ();
#line 853 "bollinger.c"
  memset (b_30, 0x0, 2);

  /* initialize field WS-PERIOD */
#line 27 "bollinger.cob"
  cob_nop ();
#line 859 "bollinger.c"
  cob_move ((cob_field *)&c_17, &f_31);

  /* initialize field WS-START-IDX */
#line 28 "bollinger.cob"
  cob_nop ();
#line 865 "bollinger.c"
  memset (b_32, 0x0, 2);

  /* initialize field WS-SUM */
#line 29 "bollinger.cob"
  cob_nop ();
#line 871 "bollinger.c"
  cob_set_packed_zero (&f_33);

  /* initialize field WS-SMA */
#line 30 "bollinger.cob"
  cob_nop ();
#line 877 "bollinger.c"
  memset (b_34, (unsigned char)'0', 7);

  /* initialize field WS-VARIANCE */
#line 31 "bollinger.cob"
  cob_nop ();
#line 883 "bollinger.c"
  cob_set_packed_zero (&f_35);

  /* initialize field WS-STD-DEV */
#line 32 "bollinger.cob"
  cob_nop ();
#line 889 "bollinger.c"
  memset (b_36, (unsigned char)'0', 7);

  /* initialize field WS-UPPER */
#line 33 "bollinger.cob"
  cob_nop ();
#line 895 "bollinger.c"
  memset (b_37, (unsigned char)'0', 7);

  /* initialize field WS-LOWER */
#line 34 "bollinger.cob"
  cob_nop ();
#line 901 "bollinger.c"
  memset (b_38, (unsigned char)'0', 7);

  /* initialize field WS-DIFF */
#line 35 "bollinger.cob"
  cob_nop ();
#line 907 "bollinger.c"
  cob_set_packed_zero (&f_39);

  /* initialize field WS-DIFF-SQ */
#line 36 "bollinger.cob"
  cob_nop ();
#line 913 "bollinger.c"
  cob_set_packed_zero (&f_40);

  /* initialize field WS-EXIT-CODE */
#line 37 "bollinger.cob"
  cob_nop ();
#line 919 "bollinger.c"
  cob_move ((cob_field *)&c_9, &f_41);

  /* initialize field WS-ERROR-MSG */
#line 38 "bollinger.cob"
  cob_nop ();
#line 925 "bollinger.c"
  memset (b_42, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'BOLLINGER' */

/* Initialize module structure for BOLLINGER */
static void BOLLINGER_module_init (cob_module *module)
{
  module->module_name = "BOLLINGER";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())BOLLINGER;
  module->module_cancel.funcptr = (void *(*)())BOLLINGER_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

