/* Generated by           cobc 3.2.0 */
/* Generated from         bollinger.cob */
/* Generated at           abr 25 2026 15:24:06 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o bollinger bollinger.cob */

/* Program local variables for 'BOLLINGER' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;
cob_decimal	*d_2 = NULL;


/* File FD-PRICES-FILE */
static cob_file		*h_FD_PRICES_FILE = NULL;
static unsigned char	h_FD_PRICES_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_19[10] __attribute__((aligned));	/* FD-PRICES-FILE Record */
static cob_u8_t	b_20[2] __attribute__((aligned));	/* WS-PRICES-STATUS */
static cob_u8_t	b_23[200] __attribute__((aligned));	/* WS-PRICES-PATH */
static cob_u8_t	b_24[4000] __attribute__((aligned));	/* WS-PRICES-TABLE */
static int	b_26;	/* WS-PRICE-IDX */
static cob_u8_t	b_28[2] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_29[2] __attribute__((aligned));	/* WS-I */
static cob_u8_t	b_30[2] __attribute__((aligned));	/* WS-J */
static cob_u8_t	b_31[1] __attribute__((aligned));	/* WS-PERIOD */
static cob_u8_t	b_32[2] __attribute__((aligned));	/* WS-START-IDX */
static cob_u8_t	b_33[7] __attribute__((aligned));	/* WS-SUM */
static cob_u8_t	b_34[7] __attribute__((aligned));	/* WS-SMA */
static cob_u8_t	b_35[7] __attribute__((aligned));	/* WS-VARIANCE */
static cob_u8_t	b_36[7] __attribute__((aligned));	/* WS-STD-DEV */
static cob_u8_t	b_37[7] __attribute__((aligned));	/* WS-UPPER */
static cob_u8_t	b_38[7] __attribute__((aligned));	/* WS-LOWER */
static cob_u8_t	b_39[4] __attribute__((aligned));	/* WS-DIFF */
static cob_u8_t	b_40[7] __attribute__((aligned));	/* WS-DIFF-SQ */
static cob_u8_t	b_41[2] __attribute__((aligned));	/* WS-EXIT-CODE */
static cob_u8_t	b_42[100] __attribute__((aligned));	/* WS-ERROR-MSG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {10, b_19, &a_3};	/* FD-PRICE-RAW */
static cob_field f_19	= {10, b_19, &a_3};	/* FD-PRICES-FILE Record */
static cob_field f_20	= {2, b_20, &a_3};	/* WS-PRICES-STATUS */
static cob_field f_23	= {200, b_23, &a_3};	/* WS-PRICES-PATH */
static cob_field f_28	= {2, b_28, &a_4};	/* WS-COUNT */
static cob_field f_29	= {2, b_29, &a_4};	/* WS-I */
static cob_field f_31	= {1, b_31, &a_5};	/* WS-PERIOD */
static cob_field f_32	= {2, b_32, &a_4};	/* WS-START-IDX */
static cob_field f_33	= {7, b_33, &a_8};	/* WS-SUM */
static cob_field f_34	= {7, b_34, &a_9};	/* WS-SMA */
static cob_field f_35	= {7, b_35, &a_8};	/* WS-VARIANCE */
static cob_field f_36	= {7, b_36, &a_9};	/* WS-STD-DEV */
static cob_field f_37	= {7, b_37, &a_9};	/* WS-UPPER */
static cob_field f_38	= {7, b_38, &a_9};	/* WS-LOWER */
static cob_field f_39	= {4, b_39, &a_10};	/* WS-DIFF */
static cob_field f_40	= {7, b_40, &a_8};	/* WS-DIFF-SQ */
static cob_field f_41	= {2, b_41, &a_7};	/* WS-EXIT-CODE */
static cob_field f_42	= {100, b_42, &a_3};	/* WS-ERROR-MSG */

/* End of fields */

