/* Generated by           cobc 3.2.0 */
/* Generated from         macd.cob */
/* Generated at           abr 25 2026 18:21:35 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o macd macd.cob */

/* Program local variables for 'MACD' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;
cob_decimal	*d_2 = NULL;
cob_decimal	*d_3 = NULL;


/* File FD-PRICES-FILE */
static cob_file		*h_FD_PRICES_FILE = NULL;
static unsigned char	h_FD_PRICES_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_19[10] __attribute__((aligned));	/* FD-PRICES-FILE Record */
static cob_u8_t	b_20[2] __attribute__((aligned));	/* WS-PRICES-STATUS */
static cob_u8_t	b_23[200] __attribute__((aligned));	/* WS-PRICES-PATH */
static cob_u8_t	b_24[4000] __attribute__((aligned));	/* WS-PRICES-TABLE */
static int	b_26;	/* WS-PRICE-IDX */
static cob_u8_t	b_28[2] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_29[2] __attribute__((aligned));	/* WS-I */
static cob_u8_t	b_30[1] __attribute__((aligned));	/* WS-FAST */
static cob_u8_t	b_31[1] __attribute__((aligned));	/* WS-SLOW */
static cob_u8_t	b_32[1] __attribute__((aligned));	/* WS-SIGNAL */
static cob_u8_t	b_33[5] __attribute__((aligned));	/* WS-EMA-FAST */
static cob_u8_t	b_34[5] __attribute__((aligned));	/* WS-EMA-SLOW */
static cob_u8_t	b_35[5] __attribute__((aligned));	/* WS-EMA-SIGNAL */
static cob_u8_t	b_36[5] __attribute__((aligned));	/* WS-MACD-LINE */
static cob_u8_t	b_37[5] __attribute__((aligned));	/* WS-HISTOGRAM */
static cob_u8_t	b_38[2] __attribute__((aligned));	/* WS-ALPHA-FAST */
static cob_u8_t	b_39[2] __attribute__((aligned));	/* WS-ALPHA-SLOW */
static cob_u8_t	b_40[2] __attribute__((aligned));	/* WS-ALPHA-SIGNAL */
static cob_u8_t	b_41[5] __attribute__((aligned));	/* WS-TEMP1 */
static cob_u8_t	b_42[5] __attribute__((aligned));	/* WS-TEMP2 */
static cob_u8_t	b_43[5] __attribute__((aligned));	/* WS-TEMP3 */
static cob_u8_t	b_44[5] __attribute__((aligned));	/* WS-TEMP4 */
static cob_u8_t	b_45[2] __attribute__((aligned));	/* WS-EXIT-CODE */
static cob_u8_t	b_46[100] __attribute__((aligned));	/* WS-ERROR-MSG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {10, b_19, &a_3};	/* FD-PRICE-RAW */
static cob_field f_19	= {10, b_19, &a_3};	/* FD-PRICES-FILE Record */
static cob_field f_20	= {2, b_20, &a_3};	/* WS-PRICES-STATUS */
static cob_field f_23	= {200, b_23, &a_3};	/* WS-PRICES-PATH */
static cob_field f_28	= {2, b_28, &a_5};	/* WS-COUNT */
static cob_field f_29	= {2, b_29, &a_5};	/* WS-I */
static cob_field f_30	= {1, b_30, &a_11};	/* WS-FAST */
static cob_field f_31	= {1, b_31, &a_11};	/* WS-SLOW */
static cob_field f_32	= {1, b_32, &a_11};	/* WS-SIGNAL */
static cob_field f_33	= {5, b_33, &a_8};	/* WS-EMA-FAST */
static cob_field f_34	= {5, b_34, &a_8};	/* WS-EMA-SLOW */
static cob_field f_35	= {5, b_35, &a_8};	/* WS-EMA-SIGNAL */
static cob_field f_36	= {5, b_36, &a_9};	/* WS-MACD-LINE */
static cob_field f_37	= {5, b_37, &a_9};	/* WS-HISTOGRAM */
static cob_field f_38	= {2, b_38, &a_7};	/* WS-ALPHA-FAST */
static cob_field f_39	= {2, b_39, &a_7};	/* WS-ALPHA-SLOW */
static cob_field f_40	= {2, b_40, &a_7};	/* WS-ALPHA-SIGNAL */
static cob_field f_41	= {5, b_41, &a_8};	/* WS-TEMP1 */
static cob_field f_42	= {5, b_42, &a_8};	/* WS-TEMP2 */
static cob_field f_43	= {5, b_43, &a_8};	/* WS-TEMP3 */
static cob_field f_44	= {5, b_44, &a_8};	/* WS-TEMP4 */
static cob_field f_45	= {2, b_45, &a_4};	/* WS-EXIT-CODE */
static cob_field f_46	= {100, b_46, &a_3};	/* WS-ERROR-MSG */

/* End of fields */

