/* Generated by           cobc 3.2.0 */
/* Generated from         macd.cob */
/* Generated at           abr 25 2026 18:21:35 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o macd macd.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"macd.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 18:21:35"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		182135

/* Global variables */
#include "macd.c.h"

/* Function prototypes */

static int		MACD ();
static int		MACD_ (const int);
static void		MACD_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MACD ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MACD' */

/* ENTRY 'MACD' */

static int
MACD ()
{
  return MACD_ (0);
}

static int
MACD_ (const int entry)
{
  /* Program local variables */
  #include "macd.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (4, &d_0, &d_1, &d_2, &d_3);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 45        : Entry     MACD                    : macd.cob */
  l_2:;
#line 45 "macd.cob"
  ENTRY_MACD:	cob_nop ();
#line 109 "macd.c"

  /* Line: 45        : Paragraph MAIN                    : macd.cob */
#line 45 "macd.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "macd.c"

  /* Line: 46        : DISPLAY            : macd.cob */
#line 46 "macd.cob"
  cob_nop ();
#line 119 "macd.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 47        : ACCEPT             : macd.cob */
#line 47 "macd.cob"
  cob_nop ();
#line 125 "macd.c"
  cob_accept_command_line (&f_23);

  /* Line: 48        : IF                 : macd.cob */
#line 48 "macd.cob"
  cob_nop ();
#line 131 "macd.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 49        : MOVE               : macd.cob */
#line 49 "macd.cob"
    cob_nop ();
#line 138 "macd.c"
    cob_move ((cob_field *)&c_3, &f_23);
  }

  /* Line: 51        : IF                 : macd.cob */
#line 51 "macd.cob"
  cob_nop ();
#line 145 "macd.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 52        : MOVE               : macd.cob */
#line 52 "macd.cob"
    cob_nop ();
#line 152 "macd.c"
    cob_move ((cob_field *)&c_4, &f_46);

    /* Line: 53        : DISPLAY            : macd.cob */
#line 53 "macd.cob"
    cob_nop ();
#line 158 "macd.c"
    cob_display (0, 1, 1, &f_46);

    /* Line: 54        : MOVE               : macd.cob */
#line 54 "macd.cob"
    cob_nop ();
#line 164 "macd.c"
    cob_move ((cob_field *)&c_1, &f_45);

    /* Line: 55        : PERFORM            : macd.cob */
#line 55 "macd.cob"
    cob_nop ();
#line 170 "macd.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_7;
    l_10:
    frame_ptr--;

    /* Line: 56        : STOP RUN           : macd.cob */
#line 56 "macd.cob"
    cob_nop ();
#line 184 "macd.c"
    cob_stop_run (b_2);
  }

  /* Line: 58        : DISPLAY            : macd.cob */
#line 58 "macd.cob"
  cob_nop ();
#line 191 "macd.c"
  cob_display (0, 1, 2, &c_5, &f_23);

  /* Line: 7         : OPEN               : WS-PRICES-LOAD.cpy */
#line 7 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 197 "macd.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_1;
    l_11:
    frame_ptr--;
  }

  /* Line: 8         : IF                 : WS-PRICES-LOAD.cpy */
#line 8 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 215 "macd.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 9         : PERFORM            : WS-PRICES-LOAD.cpy */
#line 9 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 222 "macd.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_8;
    l_12:
    frame_ptr--;
  }

  /* Line: 11        : IF                 : WS-PRICES-LOAD.cpy */
#line 11 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 237 "macd.c"
  if (((int)cob_cmpswp_s16 (b_45, 0LL) != 0))
  {

    /* Line: 12        : EXIT PARAGRAPH     : WS-PRICES-LOAD.cpy */
#line 12 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 244 "macd.c"
    goto l_5;
  }

  /* Line: 14        : MOVE               : WS-PRICES-LOAD.cpy */
#line 14 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 251 "macd.c"
  cob_move ((cob_field *)&c_6, &f_28);

  /* Line: 15        : PERFORM            : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 257 "macd.c"
  for (;;)
  {
    /* Line: 15        : UNTIL              : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 263 "macd.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 16        : READ               : WS-PRICES-LOAD.cpy */
#line 16 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 270 "macd.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 18        : SET                : WS-PRICES-LOAD.cpy */
#line 18 "WS-PRICES-LOAD.cpy"
        cob_nop ();
#line 280 "macd.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_13;
        goto l_1;
        l_13:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 20        : ADD                : WS-PRICES-LOAD.cpy */
#line 20 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 303 "macd.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 21        : COMPUTE            : WS-PRICES-LOAD.cpy */
#line 21 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 309 "macd.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_6), 1);
    }
  }

  /* Line: 25        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 25 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 318 "macd.c"
  cob_display (0, 1, 3, &c_7, &f_28, &c_8);

  /* Line: 27        : CLOSE              : WS-PRICES-LOAD.cpy */
#line 27 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 324 "macd.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_1;
    l_14:
    frame_ptr--;
  }

  /* Line: 28        : IF                 : WS-PRICES-LOAD.cpy */
#line 28 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 342 "macd.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 29        : MOVE               : WS-PRICES-LOAD.cpy */
#line 29 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 349 "macd.c"
    cob_move ((cob_field *)&c_9, &f_46);

    /* Line: 30        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 30 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 355 "macd.c"
    cob_display (0, 1, 1, &f_46);

    /* Line: 31        : MOVE               : WS-PRICES-LOAD.cpy */
#line 31 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 361 "macd.c"
    cob_move ((cob_field *)&c_1, &f_45);
  }

  /* Line: 61        : IF                 : macd.cob */
#line 61 "macd.cob"
  cob_nop ();
#line 368 "macd.c"
  if (((int)cob_cmpswp_s16 (b_45, 0LL) != 0))
  {

    /* Line: 62        : PERFORM            : macd.cob */
#line 62 "macd.cob"
    cob_nop ();
#line 375 "macd.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_7;
    l_15:
    frame_ptr--;

    /* Line: 63        : STOP RUN           : macd.cob */
#line 63 "macd.cob"
    cob_nop ();
#line 389 "macd.c"
    cob_stop_run (b_2);
  }

  /* Line: 65        : DISPLAY            : macd.cob */
#line 65 "macd.cob"
  cob_nop ();
#line 396 "macd.c"
  cob_display (0, 1, 3, &c_10, &f_28, &c_11);

  /* Line: 67        : PERFORM            : macd.cob */
#line 67 "macd.cob"
  cob_nop ();
#line 402 "macd.c"
  /* PERFORM 3000-CALCULAR-MACD */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_6;
  l_16:
  frame_ptr--;

  /* Line: 68        : DISPLAY            : macd.cob */
#line 68 "macd.cob"
  cob_nop ();
#line 416 "macd.c"
  cob_display (0, 1, 2, &c_12, &c_13);

  /* Line: 70        : PERFORM            : macd.cob */
#line 70 "macd.cob"
  cob_nop ();
#line 422 "macd.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_7;
  l_17:
  frame_ptr--;

  /* Line: 71        : STOP RUN           : macd.cob */
#line 71 "macd.cob"
  cob_nop ();
#line 436 "macd.c"
  cob_stop_run (b_2);

  /* Implicit EXIT label */
  l_5:;

  /* Line: 73        : Paragraph 3000-CALCULAR-MACD      : macd.cob */
  l_6:;
#line 73 "macd.cob"
  PARAGRAPH_3000__CALCULAR__MACD_l_6:	cob_nop ();
#line 446 "macd.c"

  /* Line: 74        : COMPUTE            : macd.cob */
#line 74 "macd.cob"
  cob_nop ();
#line 451 "macd.c"
  cob_decimal_set_llint (d_0, 2LL);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_add (d_1, dc_1);
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_38, 0);

  /* Line: 75        : COMPUTE            : macd.cob */
#line 75 "macd.cob"
  cob_nop ();
#line 461 "macd.c"
  cob_decimal_set_llint (d_0, 2LL);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_31)));
  cob_decimal_add (d_1, dc_1);
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_39, 0);

  /* Line: 76        : COMPUTE            : macd.cob */
#line 76 "macd.cob"
  cob_nop ();
#line 471 "macd.c"
  cob_decimal_set_llint (d_0, 2LL);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_32)));
  cob_decimal_add (d_1, dc_1);
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_40, 0);

  /* Line: 77        : MOVE               : macd.cob */
#line 77 "macd.cob"
  cob_nop ();
#line 481 "macd.c"
  cob_move_bcd (COB_SET_FLD (f0, 4, b_24, &a_6), &f_33);

  /* Line: 78        : MOVE               : macd.cob */
#line 78 "macd.cob"
  cob_nop ();
#line 487 "macd.c"
  cob_move_bcd (COB_SET_FLD (f0, 4, b_24, &a_6), &f_34);

  /* Line: 79        : PERFORM            : macd.cob */
#line 79 "macd.cob"
  cob_nop ();
#line 493 "macd.c"
  cob_move ((cob_field *)&c_14, &f_29);
  for (;;)
  {
    /* Line: 80        : UNTIL              : macd.cob */
#line 80 "macd.cob"
    cob_nop ();
#line 500 "macd.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) > 0))
      break;

    /* Line: 81        : COMPUTE            : macd.cob */
#line 81 "macd.cob"
    cob_nop ();
#line 507 "macd.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6));
    cob_decimal_set_field (d_1, &f_38);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_get_field (d_0, &f_41, 0);

    /* Line: 83        : COMPUTE            : macd.cob */
#line 83 "macd.cob"
    cob_nop ();
#line 516 "macd.c"
    cob_decimal_set_field (d_0, &f_33);
    cob_decimal_set_llint (d_1, 1LL);
    cob_decimal_set_field (d_2, &f_38);
    cob_decimal_sub (d_1, d_2);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_get_field (d_0, &f_42, 0);

    /* Line: 85        : COMPUTE            : macd.cob */
#line 85 "macd.cob"
    cob_nop ();
#line 527 "macd.c"
    cob_decimal_set_field (d_0, &f_41);
    cob_decimal_set_field (d_1, &f_42);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_33, 1);

    /* Line: 86        : COMPUTE            : macd.cob */
#line 86 "macd.cob"
    cob_nop ();
#line 536 "macd.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6));
    cob_decimal_set_field (d_1, &f_39);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_get_field (d_0, &f_43, 0);

    /* Line: 88        : COMPUTE            : macd.cob */
#line 88 "macd.cob"
    cob_nop ();
#line 545 "macd.c"
    cob_decimal_set_field (d_0, &f_34);
    cob_decimal_set_llint (d_1, 1LL);
    cob_decimal_set_field (d_2, &f_39);
    cob_decimal_sub (d_1, d_2);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_get_field (d_0, &f_44, 0);

    /* Line: 90        : COMPUTE            : macd.cob */
#line 90 "macd.cob"
    cob_nop ();
#line 556 "macd.c"
    cob_decimal_set_field (d_0, &f_43);
    cob_decimal_set_field (d_1, &f_44);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_34, 1);
    /* Line: 79        : VARYING            : macd.cob */
#line 79 "macd.cob"
    cob_nop ();
#line 564 "macd.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 92        : COMPUTE            : macd.cob */
#line 92 "macd.cob"
  cob_nop ();
#line 571 "macd.c"
  cob_decimal_set_field (d_0, &f_33);
  cob_decimal_set_field (d_1, &f_34);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_36, 1);

  /* Line: 93        : MOVE               : macd.cob */
#line 93 "macd.cob"
  cob_nop ();
#line 580 "macd.c"
  cob_move_bcd (&f_36, &f_35);

  /* Line: 94        : PERFORM            : macd.cob */
#line 94 "macd.cob"
  cob_nop ();
#line 586 "macd.c"
  cob_move ((cob_field *)&c_14, &f_29);
  for (;;)
  {
    /* Line: 95        : UNTIL              : macd.cob */
#line 95 "macd.cob"
    cob_nop ();
#line 593 "macd.c"
    if (((int)cob_cmpswp_u16 (b_29, (*(cob_u8_ptr) (b_32))) > 0))
      break;

    /* Line: 96        : COMPUTE            : macd.cob */
#line 96 "macd.cob"
    cob_nop ();
#line 600 "macd.c"
    cob_decimal_set_field (d_0, &f_36);
    cob_decimal_set_field (d_1, &f_40);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_set_field (d_1, &f_35);
    cob_decimal_set_llint (d_2, 1LL);
    cob_decimal_set_field (d_3, &f_40);
    cob_decimal_sub (d_2, d_3);
    cob_decimal_mul (d_1, d_2);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_35, 1);
    /* Line: 94        : VARYING            : macd.cob */
#line 94 "macd.cob"
    cob_nop ();
#line 614 "macd.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 100       : COMPUTE            : macd.cob */
#line 100 "macd.cob"
  cob_nop ();
#line 621 "macd.c"
  cob_decimal_set_field (d_0, &f_36);
  cob_decimal_set_field (d_1, &f_35);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_37, 1);

  /* Line: 102       : DISPLAY            : macd.cob */
#line 102 "macd.cob"
  cob_nop ();
#line 630 "macd.c"
  cob_display (0, 1, 5, &f_36, &c_15, &f_35, &c_15, &f_37);

  /* Line: 104       : EXIT               : macd.cob */
#line 104 "macd.cob"
  cob_nop ();
#line 636 "macd.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 106       : Paragraph 9000-FINALIZAR          : macd.cob */
  l_7:;
#line 106 "macd.cob"
  PARAGRAPH_9000__FINALIZAR_l_7:	cob_nop ();
#line 646 "macd.c"

  /* Line: 107       : CLOSE              : macd.cob */
#line 107 "macd.cob"
  cob_nop ();
#line 651 "macd.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 108       : EXIT               : macd.cob */
#line 108 "macd.cob"
  cob_nop ();
#line 669 "macd.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 110       : Paragraph 9999-MANEJAR-ERROR-FS   : macd.cob */
  l_8:;
#line 110 "macd.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_8:	cob_nop ();
#line 679 "macd.c"

  /* Line: 111       : EVALUATE           : macd.cob */
#line 111 "macd.cob"
  cob_nop ();
#line 684 "macd.c"

  /* Line: 112       : WHEN               : macd.cob */
#line 112 "macd.cob"
  cob_nop ();
#line 689 "macd.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 113       : MOVE               : macd.cob */
#line 113 "macd.cob"
    cob_nop ();
#line 697 "macd.c"
    cob_move ((cob_field *)&c_16, &f_46);
    goto l_9;
  }

  /* Line: 114       : WHEN               : macd.cob */
#line 114 "macd.cob"
  cob_nop ();
#line 705 "macd.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 115       : MOVE               : macd.cob */
#line 115 "macd.cob"
    cob_nop ();
#line 713 "macd.c"
    cob_move ((cob_field *)&c_17, &f_46);
    goto l_9;
  }

  /* WHEN OTHER */

  /* Line: 117       : STRING             : macd.cob */
#line 117 "macd.cob"
  cob_nop ();
#line 723 "macd.c"
  cob_string_init (&f_46, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_9:;

  /* Line: 120       : DISPLAY            : macd.cob */
#line 120 "macd.cob"
  cob_nop ();
#line 736 "macd.c"
  cob_display (0, 1, 1, &f_46);

  /* Line: 121       : MOVE               : macd.cob */
#line 121 "macd.cob"
  cob_nop ();
#line 742 "macd.c"
  cob_move ((cob_field *)&c_1, &f_45);

  /* Line: 122       : CLOSE              : macd.cob */
#line 122 "macd.cob"
  cob_nop ();
#line 748 "macd.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 123       : EXIT               : macd.cob */
#line 123 "macd.cob"
  cob_nop ();
#line 766 "macd.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : macd.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MACD_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 23 "macd.cob"
  cob_nop ();
#line 837 "macd.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 17 "macd.cob"
  cob_nop ();
#line 843 "macd.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 20 "macd.cob"
  cob_nop ();
#line 849 "macd.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 24 "macd.cob"
    cob_nop ();
#line 857 "macd.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_6));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 25 "macd.cob"
  cob_nop ();
#line 878 "macd.c"
  cob_move ((cob_field *)&c_6, &f_28);

  /* initialize field WS-I */
#line 26 "macd.cob"
  cob_nop ();
#line 884 "macd.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-FAST */
#line 27 "macd.cob"
  cob_nop ();
#line 890 "macd.c"
  cob_move ((cob_field *)&c_19, &f_30);

  /* initialize field WS-SLOW */
#line 28 "macd.cob"
  cob_nop ();
#line 896 "macd.c"
  cob_move ((cob_field *)&c_20, &f_31);

  /* initialize field WS-SIGNAL */
#line 29 "macd.cob"
  cob_nop ();
#line 902 "macd.c"
  cob_move ((cob_field *)&c_21, &f_32);

  /* initialize field WS-EMA-FAST */
#line 30 "macd.cob"
  cob_nop ();
#line 908 "macd.c"
  cob_set_packed_zero (&f_33);

  /* initialize field WS-EMA-SLOW */
#line 31 "macd.cob"
  cob_nop ();
#line 914 "macd.c"
  cob_set_packed_zero (&f_34);

  /* initialize field WS-EMA-SIGNAL */
#line 32 "macd.cob"
  cob_nop ();
#line 920 "macd.c"
  cob_set_packed_zero (&f_35);

  /* initialize field WS-MACD-LINE */
#line 33 "macd.cob"
  cob_nop ();
#line 926 "macd.c"
  cob_set_packed_zero (&f_36);

  /* initialize field WS-HISTOGRAM */
#line 34 "macd.cob"
  cob_nop ();
#line 932 "macd.c"
  cob_set_packed_zero (&f_37);

  /* initialize field WS-ALPHA-FAST */
#line 35 "macd.cob"
  cob_nop ();
#line 938 "macd.c"
  memset (b_38, (unsigned char)'0', 2);

  /* initialize field WS-ALPHA-SLOW */
#line 36 "macd.cob"
  cob_nop ();
#line 944 "macd.c"
  memset (b_39, (unsigned char)'0', 2);

  /* initialize field WS-ALPHA-SIGNAL */
#line 37 "macd.cob"
  cob_nop ();
#line 950 "macd.c"
  memset (b_40, (unsigned char)'0', 2);

  /* initialize field WS-TEMP1 */
#line 38 "macd.cob"
  cob_nop ();
#line 956 "macd.c"
  cob_set_packed_zero (&f_41);

  /* initialize field WS-TEMP2 */
#line 39 "macd.cob"
  cob_nop ();
#line 962 "macd.c"
  cob_set_packed_zero (&f_42);

  /* initialize field WS-TEMP3 */
#line 40 "macd.cob"
  cob_nop ();
#line 968 "macd.c"
  cob_set_packed_zero (&f_43);

  /* initialize field WS-TEMP4 */
#line 41 "macd.cob"
  cob_nop ();
#line 974 "macd.c"
  cob_set_packed_zero (&f_44);

  /* initialize field WS-EXIT-CODE */
#line 42 "macd.cob"
  cob_nop ();
#line 980 "macd.c"
  cob_move ((cob_field *)&c_6, &f_45);

  /* initialize field WS-ERROR-MSG */
#line 43 "macd.cob"
  cob_nop ();
#line 986 "macd.c"
  memset (b_46, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'MACD' */

/* Initialize module structure for MACD */
static void MACD_module_init (cob_module *module)
{
  module->module_name = "MACD";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MACD;
  module->module_cancel.funcptr = (void *(*)())MACD_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

