/* Generated by           cobc 3.2.0 */
/* Generated from         rsi.cob */
/* Generated at           abr 25 2026 15:21:34 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o rsi rsi.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"rsi.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:21:34"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		152134

/* Global variables */
#include "rsi.c.h"

/* Function prototypes */

static int		RSI ();
static int		RSI_ (const int);
static void		RSI_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (RSI ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'RSI' */

/* ENTRY 'RSI' */

static int
RSI ()
{
  return RSI_ (0);
}

static int
RSI_ (const int entry)
{
  /* Program local variables */
  #include "rsi.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (4, &d_0, &d_1, &d_2, &d_3);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 40        : Entry     RSI                     : rsi.cob */
  l_2:;
#line 40 "rsi.cob"
  ENTRY_RSI:	cob_nop ();
#line 109 "rsi.c"

  /* Line: 40        : Paragraph MAIN                    : rsi.cob */
#line 40 "rsi.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "rsi.c"

  /* Line: 41        : DISPLAY            : rsi.cob */
#line 41 "rsi.cob"
  cob_nop ();
#line 119 "rsi.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 42        : ACCEPT             : rsi.cob */
#line 42 "rsi.cob"
  cob_nop ();
#line 125 "rsi.c"
  cob_accept_command_line (&f_23);

  /* Line: 43        : IF                 : rsi.cob */
#line 43 "rsi.cob"
  cob_nop ();
#line 131 "rsi.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 44        : MOVE               : rsi.cob */
#line 44 "rsi.cob"
    cob_nop ();
#line 138 "rsi.c"
    cob_move ((cob_field *)&c_4, &f_23);
  }

  /* Line: 46        : DISPLAY            : rsi.cob */
#line 46 "rsi.cob"
  cob_nop ();
#line 145 "rsi.c"
  cob_display (0, 1, 2, &c_5, &f_23);

  /* Line: 48        : PERFORM            : rsi.cob */
#line 48 "rsi.cob"
  cob_nop ();
#line 151 "rsi.c"
  /* PERFORM 2000-LEER-PRECIOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 49        : IF                 : rsi.cob */
#line 49 "rsi.cob"
  cob_nop ();
#line 165 "rsi.c"
  if (((int)cob_cmpswp_s16 (b_40, 0LL) != 0))
  {

    /* Line: 50        : PERFORM            : rsi.cob */
#line 50 "rsi.cob"
    cob_nop ();
#line 172 "rsi.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_8;
    l_12:
    frame_ptr--;

    /* Line: 51        : STOP RUN           : rsi.cob */
#line 51 "rsi.cob"
    cob_nop ();
#line 186 "rsi.c"
    cob_stop_run (b_2);
  }

  /* Line: 53        : DISPLAY            : rsi.cob */
#line 53 "rsi.cob"
  cob_nop ();
#line 193 "rsi.c"
  cob_display (0, 1, 4, &c_6, &f_28, &c_7, &f_30);

  /* Line: 55        : PERFORM            : rsi.cob */
#line 55 "rsi.cob"
  cob_nop ();
#line 199 "rsi.c"
  /* PERFORM 3000-CALCULAR-RSI */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_7;
  l_13:
  frame_ptr--;

  /* Line: 56        : DISPLAY            : rsi.cob */
#line 56 "rsi.cob"
  cob_nop ();
#line 213 "rsi.c"
  cob_display (0, 1, 1, &c_8);

  /* Line: 57        : PERFORM            : rsi.cob */
#line 57 "rsi.cob"
  cob_nop ();
#line 219 "rsi.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_8;
  l_14:
  frame_ptr--;

  /* Line: 58        : STOP RUN           : rsi.cob */
#line 58 "rsi.cob"
  cob_nop ();
#line 233 "rsi.c"
  cob_stop_run (b_2);

  /* Line: 60        : Paragraph 2000-LEER-PRECIOS       : rsi.cob */
  l_5:;
#line 60 "rsi.cob"
  PARAGRAPH_2000__LEER__PRECIOS_l_5:	cob_nop ();
#line 240 "rsi.c"

  /* Line: 61        : OPEN               : rsi.cob */
#line 61 "rsi.cob"
  cob_nop ();
#line 245 "rsi.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_1;
    l_15:
    frame_ptr--;
  }

  /* Line: 62        : IF                 : rsi.cob */
#line 62 "rsi.cob"
  cob_nop ();
#line 263 "rsi.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 63        : PERFORM            : rsi.cob */
#line 63 "rsi.cob"
    cob_nop ();
#line 270 "rsi.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_9;
    l_16:
    frame_ptr--;
  }

  /* Line: 65        : IF                 : rsi.cob */
#line 65 "rsi.cob"
  cob_nop ();
#line 285 "rsi.c"
  if (((int)cob_cmpswp_s16 (b_40, 0LL) != 0))
  {

    /* Line: 66        : EXIT PARAGRAPH     : rsi.cob */
#line 66 "rsi.cob"
    cob_nop ();
#line 292 "rsi.c"
    goto l_6;
  }

  /* Line: 68        : MOVE               : rsi.cob */
#line 68 "rsi.cob"
  cob_nop ();
#line 299 "rsi.c"
  cob_move ((cob_field *)&c_9, &f_28);

  /* Line: 69        : PERFORM            : rsi.cob */
#line 69 "rsi.cob"
  cob_nop ();
#line 305 "rsi.c"
  for (;;)
  {
    /* Line: 69        : UNTIL              : rsi.cob */
#line 69 "rsi.cob"
    cob_nop ();
#line 311 "rsi.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 70        : READ               : rsi.cob */
#line 70 "rsi.cob"
    cob_nop ();
#line 318 "rsi.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 72        : SET                : rsi.cob */
#line 72 "rsi.cob"
        cob_nop ();
#line 328 "rsi.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_17;
        goto l_1;
        l_17:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 74        : ADD                : rsi.cob */
#line 74 "rsi.cob"
      cob_nop ();
#line 351 "rsi.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 75        : COMPUTE            : rsi.cob */
#line 75 "rsi.cob"
      cob_nop ();
#line 357 "rsi.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_6), 1);
    }
  }

  /* Line: 79        : DISPLAY            : rsi.cob */
#line 79 "rsi.cob"
  cob_nop ();
#line 366 "rsi.c"
  cob_display (0, 1, 3, &c_10, &f_28, &c_11);

  /* Line: 81        : CLOSE              : rsi.cob */
#line 81 "rsi.cob"
  cob_nop ();
#line 372 "rsi.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 82        : IF                 : rsi.cob */
#line 82 "rsi.cob"
  cob_nop ();
#line 390 "rsi.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 83        : MOVE               : rsi.cob */
#line 83 "rsi.cob"
    cob_nop ();
#line 397 "rsi.c"
    cob_move ((cob_field *)&c_12, &f_41);

    /* Line: 84        : DISPLAY            : rsi.cob */
#line 84 "rsi.cob"
    cob_nop ();
#line 403 "rsi.c"
    cob_display (0, 1, 1, &f_41);

    /* Line: 85        : MOVE               : rsi.cob */
#line 85 "rsi.cob"
    cob_nop ();
#line 409 "rsi.c"
    cob_move ((cob_field *)&c_1, &f_40);
  }

  /* Line: 87        : EXIT               : rsi.cob */
#line 87 "rsi.cob"
  cob_nop ();
#line 416 "rsi.c"

  /* Implicit EXIT label */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 89        : Paragraph 3000-CALCULAR-RSI       : rsi.cob */
  l_7:;
#line 89 "rsi.cob"
  PARAGRAPH_3000__CALCULAR__RSI_l_7:	cob_nop ();
#line 429 "rsi.c"

  /* Line: 90        : MOVE               : rsi.cob */
#line 90 "rsi.cob"
  cob_nop ();
#line 434 "rsi.c"
  cob_set_packed_zero (&f_31);

  /* Line: 91        : MOVE               : rsi.cob */
#line 91 "rsi.cob"
  cob_nop ();
#line 440 "rsi.c"
  cob_set_packed_zero (&f_32);

  /* Line: 92        : PERFORM            : rsi.cob */
#line 92 "rsi.cob"
  cob_nop ();
#line 446 "rsi.c"
  cob_move ((cob_field *)&c_2, &f_29);
  for (;;)
  {
    /* Line: 93        : UNTIL              : rsi.cob */
#line 93 "rsi.cob"
    cob_nop ();
#line 453 "rsi.c"
    if (((int)(
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_29)))),
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30))),
    cob_decimal_add (d_1, dc_1),
    cob_decimal_cmp (d_0, d_1)) > 0))
      break;

    /* Line: 94        : COMPUTE            : rsi.cob */
#line 94 "rsi.cob"
    cob_nop ();
#line 464 "rsi.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6));
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)((((unsigned short)COB_BSWAP_16(*(short *)(b_29))) - 1)) - 1), &a_6));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_37, 0);

    /* Line: 96        : IF                 : rsi.cob */
#line 96 "rsi.cob"
    cob_nop ();
#line 473 "rsi.c"
    if (((int)cob_cmp_llint (&f_37, 0LL) > 0))
    {

      /* Line: 97        : ADD                : rsi.cob */
#line 97 "rsi.cob"
      cob_nop ();
#line 480 "rsi.c"
      cob_add (&f_31, &f_37, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 99        : COMPUTE            : rsi.cob */
#line 99 "rsi.cob"
      cob_nop ();
#line 490 "rsi.c"
      cob_decimal_set_llint (d_0, 0LL);
      cob_decimal_set_field (d_1, &f_37);
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_38, 0);

      /* Line: 100       : ADD                : rsi.cob */
#line 100 "rsi.cob"
      cob_nop ();
#line 499 "rsi.c"
      cob_add (&f_32, &f_38, 0);
    }
    /* Line: 92        : VARYING            : rsi.cob */
#line 92 "rsi.cob"
    cob_nop ();
#line 505 "rsi.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 103       : COMPUTE            : rsi.cob */
#line 103 "rsi.cob"
  cob_nop ();
#line 512 "rsi.c"
  cob_decimal_set_field (d_0, &f_31);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_33, 1);

  /* Line: 104       : COMPUTE            : rsi.cob */
#line 104 "rsi.cob"
  cob_nop ();
#line 521 "rsi.c"
  cob_decimal_set_field (d_0, &f_32);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_34, 1);

  /* Line: 105       : COMPUTE            : rsi.cob */
#line 105 "rsi.cob"
  cob_nop ();
#line 530 "rsi.c"
  cob_decimal_set_ullint (d_0, (*(cob_u8_ptr) (b_30)));
  cob_decimal_add (d_0, dc_2);
  cob_decimal_get_field (d_0, &f_39, 4);

  /* Line: 106       : PERFORM            : rsi.cob */
#line 106 "rsi.cob"
  cob_nop ();
#line 538 "rsi.c"
  memcpy (b_29, b_39, 2);
  for (;;)
  {
    /* Line: 107       : UNTIL              : rsi.cob */
#line 107 "rsi.cob"
    cob_nop ();
#line 545 "rsi.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) > 0))
      break;

    /* Line: 108       : COMPUTE            : rsi.cob */
#line 108 "rsi.cob"
    cob_nop ();
#line 552 "rsi.c"
    cob_decimal_set_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6));
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)((((unsigned short)COB_BSWAP_16(*(short *)(b_29))) - 1)) - 1), &a_6));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_37, 0);

    /* Line: 110       : IF                 : rsi.cob */
#line 110 "rsi.cob"
    cob_nop ();
#line 561 "rsi.c"
    if (((int)cob_cmp_llint (&f_37, 0LL) > 0))
    {

      /* Line: 111       : COMPUTE            : rsi.cob */
#line 111 "rsi.cob"
      cob_nop ();
#line 568 "rsi.c"
      cob_decimal_set_field (d_0, &f_33);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_sub (d_1, dc_1);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_set_field (d_1, &f_37);
      cob_decimal_add (d_0, d_1);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_div (d_0, d_1);
      cob_decimal_get_field (d_0, &f_33, 1);

      /* Line: 114       : COMPUTE            : rsi.cob */
#line 114 "rsi.cob"
      cob_nop ();
#line 582 "rsi.c"
      cob_decimal_set_field (d_0, &f_34);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_sub (d_1, dc_1);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_div (d_0, d_1);
      cob_decimal_get_field (d_0, &f_34, 1);
    }
    else
    {
      /* ELSE */

      /* Line: 117       : COMPUTE            : rsi.cob */
#line 117 "rsi.cob"
      cob_nop ();
#line 598 "rsi.c"
      cob_decimal_set_llint (d_0, 0LL);
      cob_decimal_set_field (d_1, &f_37);
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_38, 0);

      /* Line: 118       : COMPUTE            : rsi.cob */
#line 118 "rsi.cob"
      cob_nop ();
#line 607 "rsi.c"
      cob_decimal_set_field (d_0, &f_33);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_sub (d_1, dc_1);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_div (d_0, d_1);
      cob_decimal_get_field (d_0, &f_33, 1);

      /* Line: 120       : COMPUTE            : rsi.cob */
#line 120 "rsi.cob"
      cob_nop ();
#line 619 "rsi.c"
      cob_decimal_set_field (d_0, &f_34);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_sub (d_1, dc_1);
      cob_decimal_mul (d_0, d_1);
      cob_decimal_set_field (d_1, &f_38);
      cob_decimal_add (d_0, d_1);
      cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
      cob_decimal_div (d_0, d_1);
      cob_decimal_get_field (d_0, &f_34, 1);
    }
    /* Line: 106       : VARYING            : rsi.cob */
#line 106 "rsi.cob"
    cob_nop ();
#line 633 "rsi.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 125       : IF                 : rsi.cob */
#line 125 "rsi.cob"
  cob_nop ();
#line 640 "rsi.c"
  if (((int)cob_cmp_llint (&f_34, 0LL) == 0))
  {

    /* Line: 126       : DISPLAY            : rsi.cob */
#line 126 "rsi.cob"
    cob_nop ();
#line 647 "rsi.c"
    cob_display (0, 1, 1, &c_13);
  }
  else
  {
    /* ELSE */

    /* Line: 128       : COMPUTE            : rsi.cob */
#line 128 "rsi.cob"
    cob_nop ();
#line 657 "rsi.c"
    cob_decimal_set_field (d_0, &f_33);
    cob_decimal_set_field (d_1, &f_34);
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_35, 1);

    /* Line: 129       : COMPUTE            : rsi.cob */
#line 129 "rsi.cob"
    cob_nop ();
#line 666 "rsi.c"
    cob_decimal_set_llint (d_0, 100LL);
    cob_decimal_set_llint (d_1, 100LL);
    cob_decimal_set_llint (d_2, 1LL);
    cob_decimal_set_field (d_3, &f_35);
    cob_decimal_add (d_2, d_3);
    cob_decimal_div (d_1, d_2);
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_36, 5);

    /* Line: 130       : DISPLAY            : rsi.cob */
#line 130 "rsi.cob"
    cob_nop ();
#line 679 "rsi.c"
    cob_display (0, 1, 1, &f_36);
  }

  /* Line: 132       : EXIT               : rsi.cob */
#line 132 "rsi.cob"
  cob_nop ();
#line 686 "rsi.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 134       : Paragraph 9000-FINALIZAR          : rsi.cob */
  l_8:;
#line 134 "rsi.cob"
  PARAGRAPH_9000__FINALIZAR_l_8:	cob_nop ();
#line 696 "rsi.c"

  /* Line: 135       : CLOSE              : rsi.cob */
#line 135 "rsi.cob"
  cob_nop ();
#line 701 "rsi.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 136       : EXIT               : rsi.cob */
#line 136 "rsi.cob"
  cob_nop ();
#line 719 "rsi.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 138       : Paragraph 9999-MANEJAR-ERROR-FS   : rsi.cob */
  l_9:;
#line 138 "rsi.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_9:	cob_nop ();
#line 729 "rsi.c"

  /* Line: 139       : EVALUATE           : rsi.cob */
#line 139 "rsi.cob"
  cob_nop ();
#line 734 "rsi.c"

  /* Line: 140       : WHEN               : rsi.cob */
#line 140 "rsi.cob"
  cob_nop ();
#line 739 "rsi.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 141       : MOVE               : rsi.cob */
#line 141 "rsi.cob"
    cob_nop ();
#line 747 "rsi.c"
    cob_move ((cob_field *)&c_14, &f_41);
    goto l_10;
  }

  /* Line: 142       : WHEN               : rsi.cob */
#line 142 "rsi.cob"
  cob_nop ();
#line 755 "rsi.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 143       : MOVE               : rsi.cob */
#line 143 "rsi.cob"
    cob_nop ();
#line 763 "rsi.c"
    cob_move ((cob_field *)&c_15, &f_41);
    goto l_10;
  }

  /* WHEN OTHER */

  /* Line: 145       : STRING             : rsi.cob */
#line 145 "rsi.cob"
  cob_nop ();
#line 773 "rsi.c"
  cob_string_init (&f_41, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_16);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_10:;

  /* Line: 148       : DISPLAY            : rsi.cob */
#line 148 "rsi.cob"
  cob_nop ();
#line 786 "rsi.c"
  cob_display (0, 1, 1, &f_41);

  /* Line: 149       : MOVE               : rsi.cob */
#line 149 "rsi.cob"
  cob_nop ();
#line 792 "rsi.c"
  cob_move ((cob_field *)&c_1, &f_40);

  /* Line: 150       : CLOSE              : rsi.cob */
#line 150 "rsi.cob"
  cob_nop ();
#line 798 "rsi.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_1;
    l_20:
    frame_ptr--;
  }

  /* Line: 151       : EXIT               : rsi.cob */
#line 151 "rsi.cob"
  cob_nop ();
#line 816 "rsi.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : rsi.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  RSI_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 23 "rsi.cob"
  cob_nop ();
#line 887 "rsi.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 17 "rsi.cob"
  cob_nop ();
#line 893 "rsi.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 20 "rsi.cob"
  cob_nop ();
#line 899 "rsi.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 24 "rsi.cob"
    cob_nop ();
#line 907 "rsi.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_6));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 25 "rsi.cob"
  cob_nop ();
#line 928 "rsi.c"
  cob_move ((cob_field *)&c_9, &f_28);

  /* initialize field WS-I */
#line 26 "rsi.cob"
  cob_nop ();
#line 934 "rsi.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-PERIOD */
#line 27 "rsi.cob"
  cob_nop ();
#line 940 "rsi.c"
  cob_move ((cob_field *)&c_17, &f_30);

  /* initialize field WS-GAIN */
#line 28 "rsi.cob"
  cob_nop ();
#line 946 "rsi.c"
  cob_set_packed_zero (&f_31);

  /* initialize field WS-LOSS */
#line 29 "rsi.cob"
  cob_nop ();
#line 952 "rsi.c"
  cob_set_packed_zero (&f_32);

  /* initialize field WS-AVG-GAIN */
#line 30 "rsi.cob"
  cob_nop ();
#line 958 "rsi.c"
  cob_set_packed_zero (&f_33);

  /* initialize field WS-AVG-LOSS */
#line 31 "rsi.cob"
  cob_nop ();
#line 964 "rsi.c"
  cob_set_packed_zero (&f_34);

  /* initialize field WS-RS */
#line 32 "rsi.cob"
  cob_nop ();
#line 970 "rsi.c"
  cob_set_packed_zero (&f_35);

  /* initialize field WS-RSI */
#line 33 "rsi.cob"
  cob_nop ();
#line 976 "rsi.c"
  memset (b_36, 0x0, 2);

  /* initialize field WS-CHANGE */
#line 34 "rsi.cob"
  cob_nop ();
#line 982 "rsi.c"
  cob_set_packed_zero (&f_37);

  /* initialize field WS-DIFF */
#line 35 "rsi.cob"
  cob_nop ();
#line 988 "rsi.c"
  cob_set_packed_zero (&f_38);

  /* initialize field WS-START-IDX */
#line 36 "rsi.cob"
  cob_nop ();
#line 994 "rsi.c"
  memset (b_39, 0x0, 2);

  /* initialize field WS-EXIT-CODE */
#line 37 "rsi.cob"
  cob_nop ();
#line 1000 "rsi.c"
  cob_move ((cob_field *)&c_9, &f_40);

  /* initialize field WS-ERROR-MSG */
#line 38 "rsi.cob"
  cob_nop ();
#line 1006 "rsi.c"
  memset (b_41, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'RSI' */

/* Initialize module structure for RSI */
static void RSI_module_init (cob_module *module)
{
  module->module_name = "RSI";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())RSI;
  module->module_cancel.funcptr = (void *(*)())RSI_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

