/* Generated by           cobc 3.2.0 */
/* Generated from         rsi.cob */
/* Generated at           abr 25 2026 18:21:35 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o rsi rsi.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x11,   4,   0, 0x0821, NULL};
static const cob_field_attr a_5 =	{0x11,   4,   0, 0x0820, NULL};
static const cob_field_attr a_6 =	{0x12,   7,   2, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x11,   2,   0, 0x0820, NULL};
static const cob_field_attr a_8 =	{0x12,   9,   2, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x12,   9,   2, 0x0001, NULL};
static const cob_field_attr a_10 =	{0x12,   8,   5, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x11,   3,   0, 0x0820, NULL};
static const cob_field_attr a_12 =	{0x10,   2,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_2	= {1, (cob_u8_ptr)"2", &a_1};
static const cob_field c_3	= {43, (cob_u8_ptr)"[DEBUG] 1000-INICIO - Programa RSI iniciado", &a_2};
static const cob_field c_4	= {10, (cob_u8_ptr)"prices.dat", &a_2};
static const cob_field c_5	= {18, (cob_u8_ptr)"ERROR: Ruta vac\303\255a", &a_2};
static const cob_field c_6	= {45, (cob_u8_ptr)"[DEBUG] 2000-LEER-PRECIOS - Leyendo archivo: ", &a_2};
static const cob_field c_7	= {1, (cob_u8_ptr)"0", &a_1};
static const cob_field c_8	= {35, (cob_u8_ptr)"[DEBUG] 2000-LEER-PRECIOS - Leidos ", &a_2};
static const cob_field c_9	= {10, (cob_u8_ptr)" registros", &a_2};
static const cob_field c_10	= {21, (cob_u8_ptr)"ERROR: Archivo vac\303\255o", &a_2};
static const cob_field c_11	= {39, (cob_u8_ptr)"[DEBUG] 3000-CALCULAR-RSI - Procesando ", &a_2};
static const cob_field c_12	= {21, (cob_u8_ptr)" precios con periodo ", &a_2};
static const cob_field c_13	= {25, (cob_u8_ptr)"[DEBUG] 9000-FINALIZAR - ", &a_2};
static const cob_field c_14	= {23, (cob_u8_ptr)"Programa RSI finalizado", &a_2};
static const cob_field c_15	= {3, (cob_u8_ptr)"100", &a_2};
static const cob_field c_16	= {28, (cob_u8_ptr)"ERROR: Archivo no encontrado", &a_2};
static const cob_field c_17	= {29, (cob_u8_ptr)"ERROR: Conflicto de atributos", &a_2};
static const cob_field c_18	= {21, (cob_u8_ptr)"ERROR: FILE STATUS = ", &a_2};
static const cob_field c_19	= {2, (cob_u8_ptr)"14", &a_12};


#define cob_nop	if (!module) cob_nop


static COB_INLINE COB_A_INLINE int
cob_cmpswp_u16 (const void *p, const cob_s64_t n)
{
	void		*x;
	unsigned short	val;
	if (unlikely(n < 0)) {
		return 1;
	}
	x = &val;
	optim_memcpy (x, p, 2);
	val = COB_BSWAP_16 (val);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmpswp_s16 (const void *p, const cob_s64_t n)
{
	short	val;
	void	*x;
	x = &val;
	optim_memcpy (x, p, 2);
	val = COB_BSWAP_16 (val);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_addswp_u16 (void *p, const int val)
{
	unsigned short	n;
	unsigned char	*x;
	unsigned char	*px = p;
	x = (unsigned char *)&n;
	x[0] = px[1];
	x[1] = px[0];
	n += val;
	px[0] = x[1];
	px[1] = x[0];
}


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;
static	cob_decimal	kc_2;
static	cob_decimal	*dc_2 = NULL;

