/* Generated by           cobc 3.2.0 */
/* Generated from         sma.cob */
/* Generated at           abr 25 2026 15:48:59 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o sma sma.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"sma.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:48:59"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		154859

/* Global variables */
#include "sma.c.h"

/* Function prototypes */

static int		SMA ();
static int		SMA_ (const int);
static void		SMA_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (SMA ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'SMA' */

/* ENTRY 'SMA' */

static int
SMA ()
{
  return SMA_ (0);
}

static int
SMA_ (const int entry)
{
  /* Program local variables */
  #include "sma.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 35        : Entry     SMA                     : sma.cob */
  l_2:;
#line 35 "sma.cob"
  ENTRY_SMA:	cob_nop ();
#line 109 "sma.c"

  /* Line: 35        : Paragraph MAIN                    : sma.cob */
#line 35 "sma.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "sma.c"

  /* Line: 36        : DISPLAY            : sma.cob */
#line 36 "sma.cob"
  cob_nop ();
#line 119 "sma.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 37        : ACCEPT             : sma.cob */
#line 37 "sma.cob"
  cob_nop ();
#line 125 "sma.c"
  cob_accept_command_line (&f_23);

  /* Line: 38        : IF                 : sma.cob */
#line 38 "sma.cob"
  cob_nop ();
#line 131 "sma.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 39        : MOVE               : sma.cob */
#line 39 "sma.cob"
    cob_nop ();
#line 138 "sma.c"
    cob_move ((cob_field *)&c_3, &f_23);
  }

  /* Line: 41        : DISPLAY            : sma.cob */
#line 41 "sma.cob"
  cob_nop ();
#line 145 "sma.c"
  cob_display (0, 1, 2, &c_4, &f_23);

  /* Line: 7         : OPEN               : WS-PRICES-LOAD.cpy */
#line 7 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 151 "sma.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_1;
    l_10:
    frame_ptr--;
  }

  /* Line: 8         : IF                 : WS-PRICES-LOAD.cpy */
#line 8 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 169 "sma.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 9         : PERFORM            : WS-PRICES-LOAD.cpy */
#line 9 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 176 "sma.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_8;
    l_11:
    frame_ptr--;
  }

  /* Line: 11        : IF                 : WS-PRICES-LOAD.cpy */
#line 11 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 191 "sma.c"
  if (((int)cob_cmpswp_s16 (b_35, 0LL) != 0))
  {

    /* Line: 12        : EXIT PARAGRAPH     : WS-PRICES-LOAD.cpy */
#line 12 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 198 "sma.c"
    goto l_5;
  }

  /* Line: 14        : MOVE               : WS-PRICES-LOAD.cpy */
#line 14 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 205 "sma.c"
  cob_move ((cob_field *)&c_5, &f_28);

  /* Line: 15        : PERFORM            : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 211 "sma.c"
  for (;;)
  {
    /* Line: 15        : UNTIL              : WS-PRICES-LOAD.cpy */
#line 15 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 217 "sma.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 16        : READ               : WS-PRICES-LOAD.cpy */
#line 16 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 224 "sma.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 18        : SET                : WS-PRICES-LOAD.cpy */
#line 18 "WS-PRICES-LOAD.cpy"
        cob_nop ();
#line 234 "sma.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_12;
        goto l_1;
        l_12:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 20        : ADD                : WS-PRICES-LOAD.cpy */
#line 20 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 257 "sma.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 21        : COMPUTE            : WS-PRICES-LOAD.cpy */
#line 21 "WS-PRICES-LOAD.cpy"
      cob_nop ();
#line 263 "sma.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_5), 1);
    }
  }

  /* Line: 25        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 25 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 272 "sma.c"
  cob_display (0, 1, 3, &c_6, &f_28, &c_7);

  /* Line: 27        : CLOSE              : WS-PRICES-LOAD.cpy */
#line 27 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 278 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_13;
    goto l_1;
    l_13:
    frame_ptr--;
  }

  /* Line: 28        : IF                 : WS-PRICES-LOAD.cpy */
#line 28 "WS-PRICES-LOAD.cpy"
  cob_nop ();
#line 296 "sma.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 29        : MOVE               : WS-PRICES-LOAD.cpy */
#line 29 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 303 "sma.c"
    cob_move ((cob_field *)&c_8, &f_36);

    /* Line: 30        : DISPLAY            : WS-PRICES-LOAD.cpy */
#line 30 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 309 "sma.c"
    cob_display (0, 1, 1, &f_36);

    /* Line: 31        : MOVE               : WS-PRICES-LOAD.cpy */
#line 31 "WS-PRICES-LOAD.cpy"
    cob_nop ();
#line 315 "sma.c"
    cob_move ((cob_field *)&c_1, &f_35);
  }

  /* Line: 44        : IF                 : sma.cob */
#line 44 "sma.cob"
  cob_nop ();
#line 322 "sma.c"
  if (((int)cob_cmpswp_s16 (b_35, 0LL) != 0))
  {

    /* Line: 45        : PERFORM            : sma.cob */
#line 45 "sma.cob"
    cob_nop ();
#line 329 "sma.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_7;
    l_14:
    frame_ptr--;

    /* Line: 46        : STOP RUN           : sma.cob */
#line 46 "sma.cob"
    cob_nop ();
#line 343 "sma.c"
    cob_stop_run (b_2);
  }

  /* Line: 48        : DISPLAY            : sma.cob */
#line 48 "sma.cob"
  cob_nop ();
#line 350 "sma.c"
  cob_display (0, 1, 4, &c_9, &f_28, &c_10, &f_30);

  /* Line: 50        : PERFORM            : sma.cob */
#line 50 "sma.cob"
  cob_nop ();
#line 356 "sma.c"
  /* PERFORM 3000-CALCULAR-SMA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_15;
  goto l_6;
  l_15:
  frame_ptr--;

  /* Line: 51        : DISPLAY            : sma.cob */
#line 51 "sma.cob"
  cob_nop ();
#line 370 "sma.c"
  cob_display (0, 1, 2, &c_11, &c_12);

  /* Line: 53        : PERFORM            : sma.cob */
#line 53 "sma.cob"
  cob_nop ();
#line 376 "sma.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_7;
  l_16:
  frame_ptr--;

  /* Line: 54        : STOP RUN           : sma.cob */
#line 54 "sma.cob"
  cob_nop ();
#line 390 "sma.c"
  cob_stop_run (b_2);

  /* Implicit EXIT label */
  l_5:;

  /* Line: 56        : Paragraph 3000-CALCULAR-SMA       : sma.cob */
  l_6:;
#line 56 "sma.cob"
  PARAGRAPH_3000__CALCULAR__SMA_l_6:	cob_nop ();
#line 400 "sma.c"

  /* Line: 57        : COMPUTE            : sma.cob */
#line 57 "sma.cob"
  cob_nop ();
#line 405 "sma.c"
  cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_28))));
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_33, 4);

  /* Line: 58        : COMPUTE            : sma.cob */
#line 58 "sma.cob"
  cob_nop ();
#line 415 "sma.c"
  cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_28))));
  cob_decimal_get_field (d_0, &f_34, 4);

  /* Line: 59        : MOVE               : sma.cob */
#line 59 "sma.cob"
  cob_nop ();
#line 422 "sma.c"
  cob_set_packed_zero (&f_31);

  /* Line: 60        : PERFORM            : sma.cob */
#line 60 "sma.cob"
  cob_nop ();
#line 428 "sma.c"
  memcpy (b_29, b_33, 2);
  for (;;)
  {
    /* Line: 61        : UNTIL              : sma.cob */
#line 61 "sma.cob"
    cob_nop ();
#line 435 "sma.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) > 0))
      break;

    /* Line: 62        : ADD                : sma.cob */
#line 62 "sma.cob"
    cob_nop ();
#line 442 "sma.c"
    cob_add (&f_31, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_5), 0);
    /* Line: 60        : VARYING            : sma.cob */
#line 60 "sma.cob"
    cob_nop ();
#line 447 "sma.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 64        : COMPUTE            : sma.cob */
#line 64 "sma.cob"
  cob_nop ();
#line 454 "sma.c"
  cob_decimal_set_field (d_0, &f_31);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_32, 1);

  /* Line: 65        : DISPLAY            : sma.cob */
#line 65 "sma.cob"
  cob_nop ();
#line 463 "sma.c"
  cob_display (0, 1, 1, &f_32);

  /* Line: 66        : EXIT               : sma.cob */
#line 66 "sma.cob"
  cob_nop ();
#line 469 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 68        : Paragraph 9000-FINALIZAR          : sma.cob */
  l_7:;
#line 68 "sma.cob"
  PARAGRAPH_9000__FINALIZAR_l_7:	cob_nop ();
#line 479 "sma.c"

  /* Line: 69        : CLOSE              : sma.cob */
#line 69 "sma.cob"
  cob_nop ();
#line 484 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }

  /* Line: 70        : EXIT               : sma.cob */
#line 70 "sma.cob"
  cob_nop ();
#line 502 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 72        : Paragraph 9999-MANEJAR-ERROR-FS   : sma.cob */
  l_8:;
#line 72 "sma.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_8:	cob_nop ();
#line 512 "sma.c"

  /* Line: 73        : EVALUATE           : sma.cob */
#line 73 "sma.cob"
  cob_nop ();
#line 517 "sma.c"

  /* Line: 74        : WHEN               : sma.cob */
#line 74 "sma.cob"
  cob_nop ();
#line 522 "sma.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 75        : MOVE               : sma.cob */
#line 75 "sma.cob"
    cob_nop ();
#line 530 "sma.c"
    cob_move ((cob_field *)&c_13, &f_36);
    goto l_9;
  }

  /* Line: 76        : WHEN               : sma.cob */
#line 76 "sma.cob"
  cob_nop ();
#line 538 "sma.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 77        : MOVE               : sma.cob */
#line 77 "sma.cob"
    cob_nop ();
#line 546 "sma.c"
    cob_move ((cob_field *)&c_14, &f_36);
    goto l_9;
  }

  /* WHEN OTHER */

  /* Line: 79        : STRING             : sma.cob */
#line 79 "sma.cob"
  cob_nop ();
#line 556 "sma.c"
  cob_string_init (&f_36, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_15);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_9:;

  /* Line: 82        : DISPLAY            : sma.cob */
#line 82 "sma.cob"
  cob_nop ();
#line 569 "sma.c"
  cob_display (0, 1, 1, &f_36);

  /* Line: 83        : MOVE               : sma.cob */
#line 83 "sma.cob"
  cob_nop ();
#line 575 "sma.c"
  cob_move ((cob_field *)&c_1, &f_35);

  /* Line: 84        : CLOSE              : sma.cob */
#line 84 "sma.cob"
  cob_nop ();
#line 581 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 85        : EXIT               : sma.cob */
#line 85 "sma.cob"
  cob_nop ();
#line 599 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : sma.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  SMA_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 23 "sma.cob"
  cob_nop ();
#line 670 "sma.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 17 "sma.cob"
  cob_nop ();
#line 676 "sma.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 20 "sma.cob"
  cob_nop ();
#line 682 "sma.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 24 "sma.cob"
    cob_nop ();
#line 690 "sma.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_5));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 25 "sma.cob"
  cob_nop ();
#line 711 "sma.c"
  cob_move ((cob_field *)&c_5, &f_28);

  /* initialize field WS-I */
#line 26 "sma.cob"
  cob_nop ();
#line 717 "sma.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-WINDOW */
#line 27 "sma.cob"
  cob_nop ();
#line 723 "sma.c"
  cob_move ((cob_field *)&c_16, &f_30);

  /* initialize field WS-SUM */
#line 28 "sma.cob"
  cob_nop ();
#line 729 "sma.c"
  cob_set_packed_zero (&f_31);

  /* initialize field WS-SMA */
#line 29 "sma.cob"
  cob_nop ();
#line 735 "sma.c"
  memset (b_32, (unsigned char)'0', 7);

  /* initialize field WS-START-IDX */
#line 30 "sma.cob"
  cob_nop ();
#line 741 "sma.c"
  memset (b_33, 0x0, 2);

  /* initialize field WS-END-IDX */
#line 31 "sma.cob"
  cob_nop ();
#line 747 "sma.c"
  memset (b_34, 0x0, 2);

  /* initialize field WS-EXIT-CODE */
#line 32 "sma.cob"
  cob_nop ();
#line 753 "sma.c"
  cob_move ((cob_field *)&c_5, &f_35);

  /* initialize field WS-ERROR-MSG */
#line 33 "sma.cob"
  cob_nop ();
#line 759 "sma.c"
  memset (b_36, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'SMA' */

/* Initialize module structure for SMA */
static void SMA_module_init (cob_module *module)
{
  module->module_name = "SMA";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())SMA;
  module->module_cancel.funcptr = (void *(*)())SMA_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

