/* Generated by           cobc 3.2.0 */
/* Generated from         sma.cob */
/* Generated at           abr 25 2026 15:19:32 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o sma sma.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"sma.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:19:32"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		151932

/* Global variables */
#include "sma.c.h"

/* Function prototypes */

static int		SMA ();
static int		SMA_ (const int);
static void		SMA_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (SMA ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'SMA' */

/* ENTRY 'SMA' */

static int
SMA ()
{
  return SMA_ (0);
}

static int
SMA_ (const int entry)
{
  /* Program local variables */
  #include "sma.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 35        : Entry     SMA                     : sma.cob */
  l_2:;
#line 35 "sma.cob"
  ENTRY_SMA:	cob_nop ();
#line 109 "sma.c"

  /* Line: 35        : Paragraph MAIN                    : sma.cob */
#line 35 "sma.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "sma.c"

  /* Line: 36        : DISPLAY            : sma.cob */
#line 36 "sma.cob"
  cob_nop ();
#line 119 "sma.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 37        : ACCEPT             : sma.cob */
#line 37 "sma.cob"
  cob_nop ();
#line 125 "sma.c"
  cob_accept_command_line (&f_23);

  /* Line: 38        : IF                 : sma.cob */
#line 38 "sma.cob"
  cob_nop ();
#line 131 "sma.c"
  if (((int)memcmp (b_23, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 39        : MOVE               : sma.cob */
#line 39 "sma.cob"
    cob_nop ();
#line 138 "sma.c"
    cob_move ((cob_field *)&c_3, &f_23);
  }

  /* Line: 41        : DISPLAY            : sma.cob */
#line 41 "sma.cob"
  cob_nop ();
#line 145 "sma.c"
  cob_display (0, 1, 2, &c_4, &f_23);

  /* Line: 43        : PERFORM            : sma.cob */
#line 43 "sma.cob"
  cob_nop ();
#line 151 "sma.c"
  /* PERFORM 2000-LEER-PRECIOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 44        : IF                 : sma.cob */
#line 44 "sma.cob"
  cob_nop ();
#line 165 "sma.c"
  if (((int)cob_cmpswp_s16 (b_35, 0LL) != 0))
  {

    /* Line: 45        : PERFORM            : sma.cob */
#line 45 "sma.cob"
    cob_nop ();
#line 172 "sma.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_8;
    l_12:
    frame_ptr--;

    /* Line: 46        : STOP RUN           : sma.cob */
#line 46 "sma.cob"
    cob_nop ();
#line 186 "sma.c"
    cob_stop_run (b_2);
  }

  /* Line: 48        : DISPLAY            : sma.cob */
#line 48 "sma.cob"
  cob_nop ();
#line 193 "sma.c"
  cob_display (0, 1, 4, &c_5, &f_28, &c_6, &f_30);

  /* Line: 50        : PERFORM            : sma.cob */
#line 50 "sma.cob"
  cob_nop ();
#line 199 "sma.c"
  /* PERFORM 3000-CALCULAR-SMA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_7;
  l_13:
  frame_ptr--;

  /* Line: 51        : DISPLAY            : sma.cob */
#line 51 "sma.cob"
  cob_nop ();
#line 213 "sma.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 52        : PERFORM            : sma.cob */
#line 52 "sma.cob"
  cob_nop ();
#line 219 "sma.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_8;
  l_14:
  frame_ptr--;

  /* Line: 53        : STOP RUN           : sma.cob */
#line 53 "sma.cob"
  cob_nop ();
#line 233 "sma.c"
  cob_stop_run (b_2);

  /* Line: 55        : Paragraph 2000-LEER-PRECIOS       : sma.cob */
  l_5:;
#line 55 "sma.cob"
  PARAGRAPH_2000__LEER__PRECIOS_l_5:	cob_nop ();
#line 240 "sma.c"

  /* Line: 56        : OPEN               : sma.cob */
#line 56 "sma.cob"
  cob_nop ();
#line 245 "sma.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_20);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_1;
    l_15:
    frame_ptr--;
  }

  /* Line: 57        : IF                 : sma.cob */
#line 57 "sma.cob"
  cob_nop ();
#line 263 "sma.c"
  if (!((int)memcmp (b_20, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 58        : PERFORM            : sma.cob */
#line 58 "sma.cob"
    cob_nop ();
#line 270 "sma.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_9;
    l_16:
    frame_ptr--;
  }

  /* Line: 60        : IF                 : sma.cob */
#line 60 "sma.cob"
  cob_nop ();
#line 285 "sma.c"
  if (((int)cob_cmpswp_s16 (b_35, 0LL) != 0))
  {

    /* Line: 61        : EXIT PARAGRAPH     : sma.cob */
#line 61 "sma.cob"
    cob_nop ();
#line 292 "sma.c"
    goto l_6;
  }

  /* Line: 63        : MOVE               : sma.cob */
#line 63 "sma.cob"
  cob_nop ();
#line 299 "sma.c"
  cob_move ((cob_field *)&c_8, &f_28);

  /* Line: 64        : PERFORM            : sma.cob */
#line 64 "sma.cob"
  cob_nop ();
#line 305 "sma.c"
  for (;;)
  {
    /* Line: 64        : UNTIL              : sma.cob */
#line 64 "sma.cob"
    cob_nop ();
#line 311 "sma.c"
    if (((int)memcmp (b_20, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 65        : READ               : sma.cob */
#line 65 "sma.cob"
    cob_nop ();
#line 318 "sma.c"
    cob_read_next (h_FD_PRICES_FILE, &f_20, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 67        : SET                : sma.cob */
#line 67 "sma.cob"
        cob_nop ();
#line 328 "sma.c"
        memcpy (b_20, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_17;
        goto l_1;
        l_17:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_19, b_19, 10);

      /* Line: 69        : ADD                : sma.cob */
#line 69 "sma.cob"
      cob_nop ();
#line 351 "sma.c"
      cob_add (&f_28, (cob_field *)&c_1, 4);

      /* Line: 70        : COMPUTE            : sma.cob */
#line 70 "sma.cob"
      cob_nop ();
#line 357 "sma.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_28)))) - 1), &a_6), 1);
    }
  }

  /* Line: 74        : DISPLAY            : sma.cob */
#line 74 "sma.cob"
  cob_nop ();
#line 366 "sma.c"
  cob_display (0, 1, 3, &c_9, &f_28, &c_10);

  /* Line: 76        : CLOSE              : sma.cob */
#line 76 "sma.cob"
  cob_nop ();
#line 372 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 77        : IF                 : sma.cob */
#line 77 "sma.cob"
  cob_nop ();
#line 390 "sma.c"
  if (((int)cob_cmpswp_u16 (b_28, 0LL) == 0))
  {

    /* Line: 78        : MOVE               : sma.cob */
#line 78 "sma.cob"
    cob_nop ();
#line 397 "sma.c"
    cob_move ((cob_field *)&c_11, &f_36);

    /* Line: 79        : DISPLAY            : sma.cob */
#line 79 "sma.cob"
    cob_nop ();
#line 403 "sma.c"
    cob_display (0, 1, 1, &f_36);

    /* Line: 80        : MOVE               : sma.cob */
#line 80 "sma.cob"
    cob_nop ();
#line 409 "sma.c"
    cob_move ((cob_field *)&c_1, &f_35);
  }

  /* Line: 82        : EXIT               : sma.cob */
#line 82 "sma.cob"
  cob_nop ();
#line 416 "sma.c"

  /* Implicit EXIT label */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 84        : Paragraph 3000-CALCULAR-SMA       : sma.cob */
  l_7:;
#line 84 "sma.cob"
  PARAGRAPH_3000__CALCULAR__SMA_l_7:	cob_nop ();
#line 429 "sma.c"

  /* Line: 85        : COMPUTE            : sma.cob */
#line 85 "sma.cob"
  cob_nop ();
#line 434 "sma.c"
  cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_28))));
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_33, 4);

  /* Line: 86        : COMPUTE            : sma.cob */
#line 86 "sma.cob"
  cob_nop ();
#line 444 "sma.c"
  cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_28))));
  cob_decimal_get_field (d_0, &f_34, 4);

  /* Line: 87        : MOVE               : sma.cob */
#line 87 "sma.cob"
  cob_nop ();
#line 451 "sma.c"
  cob_set_packed_zero (&f_31);

  /* Line: 88        : PERFORM            : sma.cob */
#line 88 "sma.cob"
  cob_nop ();
#line 457 "sma.c"
  memcpy (b_29, b_33, 2);
  for (;;)
  {
    /* Line: 89        : UNTIL              : sma.cob */
#line 89 "sma.cob"
    cob_nop ();
#line 464 "sma.c"
    if (((int)cob_cmpswp_u16 (b_29, ((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) > 0))
      break;

    /* Line: 90        : ADD                : sma.cob */
#line 90 "sma.cob"
    cob_nop ();
#line 471 "sma.c"
    cob_add (&f_31, COB_SET_FLD (f0, 4, b_24 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_29)))) - 1), &a_6), 0);
    /* Line: 88        : VARYING            : sma.cob */
#line 88 "sma.cob"
    cob_nop ();
#line 476 "sma.c"
    cob_addswp_u16 (b_29, 1);
  }

  /* Line: 92        : COMPUTE            : sma.cob */
#line 92 "sma.cob"
  cob_nop ();
#line 483 "sma.c"
  cob_decimal_set_field (d_0, &f_31);
  cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_30)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_get_field (d_0, &f_32, 1);

  /* Line: 93        : DISPLAY            : sma.cob */
#line 93 "sma.cob"
  cob_nop ();
#line 492 "sma.c"
  cob_display (0, 1, 1, &f_32);

  /* Line: 94        : EXIT               : sma.cob */
#line 94 "sma.cob"
  cob_nop ();
#line 498 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 96        : Paragraph 9000-FINALIZAR          : sma.cob */
  l_8:;
#line 96 "sma.cob"
  PARAGRAPH_9000__FINALIZAR_l_8:	cob_nop ();
#line 508 "sma.c"

  /* Line: 97        : CLOSE              : sma.cob */
#line 97 "sma.cob"
  cob_nop ();
#line 513 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 98        : EXIT               : sma.cob */
#line 98 "sma.cob"
  cob_nop ();
#line 531 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 100       : Paragraph 9999-MANEJAR-ERROR-FS   : sma.cob */
  l_9:;
#line 100 "sma.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_9:	cob_nop ();
#line 541 "sma.c"

  /* Line: 101       : EVALUATE           : sma.cob */
#line 101 "sma.cob"
  cob_nop ();
#line 546 "sma.c"

  /* Line: 102       : WHEN               : sma.cob */
#line 102 "sma.cob"
  cob_nop ();
#line 551 "sma.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 103       : MOVE               : sma.cob */
#line 103 "sma.cob"
    cob_nop ();
#line 559 "sma.c"
    cob_move ((cob_field *)&c_12, &f_36);
    goto l_10;
  }

  /* Line: 104       : WHEN               : sma.cob */
#line 104 "sma.cob"
  cob_nop ();
#line 567 "sma.c"

  if (((int)memcmp (b_20, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 105       : MOVE               : sma.cob */
#line 105 "sma.cob"
    cob_nop ();
#line 575 "sma.c"
    cob_move ((cob_field *)&c_13, &f_36);
    goto l_10;
  }

  /* WHEN OTHER */

  /* Line: 107       : STRING             : sma.cob */
#line 107 "sma.cob"
  cob_nop ();
#line 585 "sma.c"
  cob_string_init (&f_36, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_14);
  cob_string_append (&f_20);
  cob_string_finish ();

  /* End EVALUATE */
  l_10:;

  /* Line: 110       : DISPLAY            : sma.cob */
#line 110 "sma.cob"
  cob_nop ();
#line 598 "sma.c"
  cob_display (0, 1, 1, &f_36);

  /* Line: 111       : MOVE               : sma.cob */
#line 111 "sma.cob"
  cob_nop ();
#line 604 "sma.c"
  cob_move ((cob_field *)&c_1, &f_35);

  /* Line: 112       : CLOSE              : sma.cob */
#line 112 "sma.cob"
  cob_nop ();
#line 610 "sma.c"
  cob_close (h_FD_PRICES_FILE, &f_20, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_1;
    l_20:
    frame_ptr--;
  }

  /* Line: 113       : EXIT               : sma.cob */
#line 113 "sma.cob"
  cob_nop ();
#line 628 "sma.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : sma.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  SMA_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 23 "sma.cob"
  cob_nop ();
#line 699 "sma.c"
  b_26 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 17 "sma.cob"
  cob_nop ();
#line 705 "sma.c"
  memset (b_20, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 20 "sma.cob"
  cob_nop ();
#line 711 "sma.c"
  memset (b_23, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-PRICE-COMP3 */
#line 24 "sma.cob"
    cob_nop ();
#line 719 "sma.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_24, &a_6));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +      4, b_ptr,      4);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +      8, b_ptr,      8);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     16, b_ptr,     16);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     32, b_ptr,     32);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +     64, b_ptr,     64);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    128, b_ptr,    128);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    256, b_ptr,    256);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +    512, b_ptr,    512);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   1024, b_ptr,   1024);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   2048, b_ptr,   1952);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 25 "sma.cob"
  cob_nop ();
#line 740 "sma.c"
  cob_move ((cob_field *)&c_8, &f_28);

  /* initialize field WS-I */
#line 26 "sma.cob"
  cob_nop ();
#line 746 "sma.c"
  memset (b_29, 0x0, 2);

  /* initialize field WS-WINDOW */
#line 27 "sma.cob"
  cob_nop ();
#line 752 "sma.c"
  cob_move ((cob_field *)&c_15, &f_30);

  /* initialize field WS-SUM */
#line 28 "sma.cob"
  cob_nop ();
#line 758 "sma.c"
  cob_set_packed_zero (&f_31);

  /* initialize field WS-SMA */
#line 29 "sma.cob"
  cob_nop ();
#line 764 "sma.c"
  memset (b_32, (unsigned char)'0', 7);

  /* initialize field WS-START-IDX */
#line 30 "sma.cob"
  cob_nop ();
#line 770 "sma.c"
  memset (b_33, 0x0, 2);

  /* initialize field WS-END-IDX */
#line 31 "sma.cob"
  cob_nop ();
#line 776 "sma.c"
  memset (b_34, 0x0, 2);

  /* initialize field WS-EXIT-CODE */
#line 32 "sma.cob"
  cob_nop ();
#line 782 "sma.c"
  cob_move ((cob_field *)&c_8, &f_35);

  /* initialize field WS-ERROR-MSG */
#line 33 "sma.cob"
  cob_nop ();
#line 788 "sma.c"
  memset (b_36, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_23;
  h_FD_PRICES_FILE->record = &f_19;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 10;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'SMA' */

/* Initialize module structure for SMA */
static void SMA_module_init (cob_module *module)
{
  module->module_name = "SMA";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())SMA;
  module->module_cancel.funcptr = (void *(*)())SMA_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

