/* Generated by           cobc 3.2.0 */
/* Generated from         stochastic.cob */
/* Generated at           abr 25 2026 15:27:17 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o stochastic stochastic.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"stochastic.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"abr 25 2026 15:27:17"
#define  COB_MODULE_DATE		20260425
#define  COB_MODULE_TIME		152717

/* Global variables */
#include "stochastic.c.h"

/* Function prototypes */

static int		STOCHASTIC ();
static int		STOCHASTIC_ (const int);
static void		STOCHASTIC_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (STOCHASTIC ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'STOCHASTIC' */

/* ENTRY 'STOCHASTIC' */

static int
STOCHASTIC ()
{
  return STOCHASTIC_ (0);
}

static int
STOCHASTIC_ (const int entry)
{
  /* Program local variables */
  #include "stochastic.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (3, &d_0, &d_1, &d_2);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 45        : Entry     STOCHASTIC              : stochastic.cob */
  l_2:;
#line 45 "stochastic.cob"
  ENTRY_STOCHASTIC:	cob_nop ();
#line 109 "stochastic.c"

  /* Line: 45        : Paragraph MAIN                    : stochastic.cob */
#line 45 "stochastic.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 114 "stochastic.c"

  /* Line: 46        : DISPLAY            : stochastic.cob */
#line 46 "stochastic.cob"
  cob_nop ();
#line 119 "stochastic.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 47        : ACCEPT             : stochastic.cob */
#line 47 "stochastic.cob"
  cob_nop ();
#line 125 "stochastic.c"
  cob_accept_command_line (&f_27);

  /* Line: 48        : IF                 : stochastic.cob */
#line 48 "stochastic.cob"
  cob_nop ();
#line 131 "stochastic.c"
  if (((int)memcmp (b_27, COB_SPACES_ALPHABETIC, 200) == 0))
  {

    /* Line: 49        : MOVE               : stochastic.cob */
#line 49 "stochastic.cob"
    cob_nop ();
#line 138 "stochastic.c"
    cob_move ((cob_field *)&c_4, &f_27);
  }

  /* Line: 51        : DISPLAY            : stochastic.cob */
#line 51 "stochastic.cob"
  cob_nop ();
#line 145 "stochastic.c"
  cob_display (0, 1, 2, &c_5, &f_27);

  /* Line: 53        : PERFORM            : stochastic.cob */
#line 53 "stochastic.cob"
  cob_nop ();
#line 151 "stochastic.c"
  /* PERFORM 2000-LEER-PRECIOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 54        : IF                 : stochastic.cob */
#line 54 "stochastic.cob"
  cob_nop ();
#line 165 "stochastic.c"
  if (((int)cob_cmpswp_s16 (b_46, 0LL) != 0))
  {

    /* Line: 55        : PERFORM            : stochastic.cob */
#line 55 "stochastic.cob"
    cob_nop ();
#line 172 "stochastic.c"
    /* PERFORM 9000-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_8;
    l_12:
    frame_ptr--;

    /* Line: 56        : STOP RUN           : stochastic.cob */
#line 56 "stochastic.cob"
    cob_nop ();
#line 186 "stochastic.c"
    cob_stop_run (b_2);
  }

  /* Line: 58        : DISPLAY            : stochastic.cob */
#line 58 "stochastic.cob"
  cob_nop ();
#line 193 "stochastic.c"
  cob_display (0, 1, 6, &c_6, &f_34, &c_7, &f_37, &c_8, &f_38);

  /* Line: 60        : PERFORM            : stochastic.cob */
#line 60 "stochastic.cob"
  cob_nop ();
#line 199 "stochastic.c"
  /* PERFORM 3000-CALCULAR-STOCH */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_7;
  l_13:
  frame_ptr--;

  /* Line: 61        : DISPLAY            : stochastic.cob */
#line 61 "stochastic.cob"
  cob_nop ();
#line 213 "stochastic.c"
  cob_display (0, 1, 2, &c_9, &c_10);

  /* Line: 63        : PERFORM            : stochastic.cob */
#line 63 "stochastic.cob"
  cob_nop ();
#line 219 "stochastic.c"
  /* PERFORM 9000-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_8;
  l_14:
  frame_ptr--;

  /* Line: 64        : STOP RUN           : stochastic.cob */
#line 64 "stochastic.cob"
  cob_nop ();
#line 233 "stochastic.c"
  cob_stop_run (b_2);

  /* Line: 66        : Paragraph 2000-LEER-PRECIOS       : stochastic.cob */
  l_5:;
#line 66 "stochastic.cob"
  PARAGRAPH_2000__LEER__PRECIOS_l_5:	cob_nop ();
#line 240 "stochastic.c"

  /* Line: 67        : OPEN               : stochastic.cob */
#line 67 "stochastic.cob"
  cob_nop ();
#line 245 "stochastic.c"
  cob_open (h_FD_PRICES_FILE, COB_OPEN_INPUT, 0, &f_24);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_1;
    l_15:
    frame_ptr--;
  }

  /* Line: 68        : IF                 : stochastic.cob */
#line 68 "stochastic.cob"
  cob_nop ();
#line 263 "stochastic.c"
  if (!((int)memcmp (b_24, (cob_u8_ptr)"00", 2) == 0))
  {

    /* Line: 69        : PERFORM            : stochastic.cob */
#line 69 "stochastic.cob"
    cob_nop ();
#line 270 "stochastic.c"
    /* PERFORM 9999-MANEJAR-ERROR-FS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_9;
    l_16:
    frame_ptr--;
  }

  /* Line: 71        : IF                 : stochastic.cob */
#line 71 "stochastic.cob"
  cob_nop ();
#line 285 "stochastic.c"
  if (((int)cob_cmpswp_s16 (b_46, 0LL) != 0))
  {

    /* Line: 72        : EXIT PARAGRAPH     : stochastic.cob */
#line 72 "stochastic.cob"
    cob_nop ();
#line 292 "stochastic.c"
    goto l_6;
  }

  /* Line: 74        : MOVE               : stochastic.cob */
#line 74 "stochastic.cob"
  cob_nop ();
#line 299 "stochastic.c"
  cob_move ((cob_field *)&c_11, &f_34);

  /* Line: 75        : PERFORM            : stochastic.cob */
#line 75 "stochastic.cob"
  cob_nop ();
#line 305 "stochastic.c"
  for (;;)
  {
    /* Line: 75        : UNTIL              : stochastic.cob */
#line 75 "stochastic.cob"
    cob_nop ();
#line 311 "stochastic.c"
    if (((int)memcmp (b_24, (cob_u8_ptr)"10", 2) == 0))
      break;

    /* Line: 76        : READ               : stochastic.cob */
#line 76 "stochastic.cob"
    cob_nop ();
#line 318 "stochastic.c"
    cob_read_next (h_FD_PRICES_FILE, &f_24, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 78        : SET                : stochastic.cob */
#line 78 "stochastic.cob"
        cob_nop ();
#line 328 "stochastic.c"
        memcpy (b_24, "10", 2);
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_17;
        goto l_1;
        l_17:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_23, b_23, 32);

      /* Line: 80        : ADD                : stochastic.cob */
#line 80 "stochastic.cob"
      cob_nop ();
#line 351 "stochastic.c"
      cob_add (&f_34, (cob_field *)&c_1, 4);

      /* Line: 81        : COMPUTE            : stochastic.cob */
#line 81 "stochastic.cob"
      cob_nop ();
#line 357 "stochastic.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_18));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_7), 1);

      /* Line: 83        : COMPUTE            : stochastic.cob */
#line 83 "stochastic.cob"
      cob_nop ();
#line 364 "stochastic.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_20));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_7), 1);

      /* Line: 85        : COMPUTE            : stochastic.cob */
#line 85 "stochastic.cob"
      cob_nop ();
#line 371 "stochastic.c"
      cob_decimal_set_field (d_0, cob_intr_numval (&f_22));
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_28 + 8 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) - 1), &a_7), 1);
    }
  }

  /* Line: 89        : DISPLAY            : stochastic.cob */
#line 89 "stochastic.cob"
  cob_nop ();
#line 380 "stochastic.c"
  cob_display (0, 1, 3, &c_12, &f_34, &c_13);

  /* Line: 91        : CLOSE              : stochastic.cob */
#line 91 "stochastic.cob"
  cob_nop ();
#line 386 "stochastic.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 92        : IF                 : stochastic.cob */
#line 92 "stochastic.cob"
  cob_nop ();
#line 404 "stochastic.c"
  if (((int)cob_cmpswp_u16 (b_34, 0LL) == 0))
  {

    /* Line: 93        : MOVE               : stochastic.cob */
#line 93 "stochastic.cob"
    cob_nop ();
#line 411 "stochastic.c"
    cob_move ((cob_field *)&c_14, &f_47);

    /* Line: 94        : DISPLAY            : stochastic.cob */
#line 94 "stochastic.cob"
    cob_nop ();
#line 417 "stochastic.c"
    cob_display (0, 1, 1, &f_47);

    /* Line: 95        : MOVE               : stochastic.cob */
#line 95 "stochastic.cob"
    cob_nop ();
#line 423 "stochastic.c"
    cob_move ((cob_field *)&c_1, &f_46);
  }

  /* Line: 97        : EXIT               : stochastic.cob */
#line 97 "stochastic.cob"
  cob_nop ();
#line 430 "stochastic.c"

  /* Implicit EXIT label */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 99        : Paragraph 3000-CALCULAR-STOCH     : stochastic.cob */
  l_7:;
#line 99 "stochastic.cob"
  PARAGRAPH_3000__CALCULAR__STOCH_l_7:	cob_nop ();
#line 443 "stochastic.c"

  /* Line: 100       : PERFORM            : stochastic.cob */
#line 100 "stochastic.cob"
  cob_nop ();
#line 448 "stochastic.c"
  cob_move (&f_37, &f_35);
  for (;;)
  {
    /* Line: 101       : UNTIL              : stochastic.cob */
#line 101 "stochastic.cob"
    cob_nop ();
#line 455 "stochastic.c"
    if (((int)cob_cmpswp_u16 (b_35, ((unsigned short)COB_BSWAP_16(*(short *)(b_34)))) > 0))
      break;

    /* Line: 102       : MOVE               : stochastic.cob */
#line 102 "stochastic.cob"
    cob_nop ();
#line 462 "stochastic.c"
    memcpy (b_39, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), 4);

    /* Line: 103       : MOVE               : stochastic.cob */
#line 103 "stochastic.cob"
    cob_nop ();
#line 468 "stochastic.c"
    memcpy (b_40, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), 4);

    /* Line: 104       : COMPUTE            : stochastic.cob */
#line 104 "stochastic.cob"
    cob_nop ();
#line 474 "stochastic.c"
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_35))));
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_37)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_44, 4);

    /* Line: 105       : PERFORM            : stochastic.cob */
#line 105 "stochastic.cob"
    cob_nop ();
#line 484 "stochastic.c"
    memcpy (b_36, b_44, 2);
    for (;;)
    {
      /* Line: 106       : UNTIL              : stochastic.cob */
#line 106 "stochastic.cob"
      cob_nop ();
#line 491 "stochastic.c"
      if (((int)cob_cmpswp_u16 (b_36, ((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) > 0))
        break;

      /* Line: 107       : IF                 : stochastic.cob */
#line 107 "stochastic.cob"
      cob_nop ();
#line 498 "stochastic.c"
      if (((int)cob_bcd_cmp (COB_SET_FLD (f0, 4, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_36)))) - 1), &a_7), &f_39) > 0))
      {

        /* Line: 108       : MOVE               : stochastic.cob */
#line 108 "stochastic.cob"
        cob_nop ();
#line 505 "stochastic.c"
        memcpy (b_39, b_28 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_36)))) - 1), 4);
      }

      /* Line: 110       : IF                 : stochastic.cob */
#line 110 "stochastic.cob"
      cob_nop ();
#line 512 "stochastic.c"
      if (((int)cob_bcd_cmp (COB_SET_FLD (f0, 4, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_36)))) - 1), &a_7), &f_40) < 0))
      {

        /* Line: 111       : MOVE               : stochastic.cob */
#line 111 "stochastic.cob"
        cob_nop ();
#line 519 "stochastic.c"
        memcpy (b_40, b_28 + 4 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_36)))) - 1), 4);
      }
      /* Line: 105       : VARYING            : stochastic.cob */
#line 105 "stochastic.cob"
      cob_nop ();
#line 525 "stochastic.c"
      cob_addswp_u16 (b_36, 1);
    }

    /* Line: 114       : COMPUTE            : stochastic.cob */
#line 114 "stochastic.cob"
    cob_nop ();
#line 532 "stochastic.c"
    cob_decimal_set_llint (d_0, 100LL);
    cob_decimal_set_field (d_1, COB_SET_FLD (f0, 4, b_28 + 8 + 12LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) - 1), &a_7));
    cob_decimal_set_field (d_2, &f_40);
    cob_decimal_sub (d_1, d_2);
    cob_decimal_mul (d_0, d_1);
    cob_decimal_set_field (d_1, &f_39);
    cob_decimal_set_field (d_2, &f_40);
    cob_decimal_sub (d_1, d_2);
    cob_decimal_add (d_1, dc_2);
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_41, 1);

    /* Line: 117       : MOVE               : stochastic.cob */
#line 117 "stochastic.cob"
    cob_nop ();
#line 548 "stochastic.c"
    cob_set_packed_zero (&f_43);

    /* Line: 118       : COMPUTE            : stochastic.cob */
#line 118 "stochastic.cob"
    cob_nop ();
#line 554 "stochastic.c"
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_35))));
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_38)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_45, 4);

    /* Line: 119       : PERFORM            : stochastic.cob */
#line 119 "stochastic.cob"
    cob_nop ();
#line 564 "stochastic.c"
    memcpy (b_36, b_45, 2);
    for (;;)
    {
      /* Line: 120       : UNTIL              : stochastic.cob */
#line 120 "stochastic.cob"
      cob_nop ();
#line 571 "stochastic.c"
      if (((int)cob_cmpswp_u16 (b_36, ((unsigned short)COB_BSWAP_16(*(short *)(b_35)))) > 0))
        break;

      /* Line: 121       : ADD                : stochastic.cob */
#line 121 "stochastic.cob"
      cob_nop ();
#line 578 "stochastic.c"
      cob_add (&f_43, &f_41, 0);
      /* Line: 119       : VARYING            : stochastic.cob */
#line 119 "stochastic.cob"
      cob_nop ();
#line 583 "stochastic.c"
      cob_addswp_u16 (b_36, 1);
    }

    /* Line: 123       : COMPUTE            : stochastic.cob */
#line 123 "stochastic.cob"
    cob_nop ();
#line 590 "stochastic.c"
    cob_decimal_set_field (d_0, &f_43);
    cob_decimal_set_ullint (d_1, (*(cob_u8_ptr) (b_38)));
    cob_decimal_div (d_0, d_1);
    cob_decimal_get_field (d_0, &f_42, 1);

    /* Line: 124       : DISPLAY            : stochastic.cob */
#line 124 "stochastic.cob"
    cob_nop ();
#line 599 "stochastic.c"
    cob_display (0, 1, 3, &f_41, &c_15, &f_42);
    /* Line: 100       : VARYING            : stochastic.cob */
#line 100 "stochastic.cob"
    cob_nop ();
#line 604 "stochastic.c"
    cob_addswp_u16 (b_35, 1);
  }

  /* Line: 126       : EXIT               : stochastic.cob */
#line 126 "stochastic.cob"
  cob_nop ();
#line 611 "stochastic.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 128       : Paragraph 9000-FINALIZAR          : stochastic.cob */
  l_8:;
#line 128 "stochastic.cob"
  PARAGRAPH_9000__FINALIZAR_l_8:	cob_nop ();
#line 621 "stochastic.c"

  /* Line: 129       : CLOSE              : stochastic.cob */
#line 129 "stochastic.cob"
  cob_nop ();
#line 626 "stochastic.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 130       : EXIT               : stochastic.cob */
#line 130 "stochastic.cob"
  cob_nop ();
#line 644 "stochastic.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 132       : Paragraph 9999-MANEJAR-ERROR-FS   : stochastic.cob */
  l_9:;
#line 132 "stochastic.cob"
  PARAGRAPH_9999__MANEJAR__ERROR__FS_l_9:	cob_nop ();
#line 654 "stochastic.c"

  /* Line: 133       : EVALUATE           : stochastic.cob */
#line 133 "stochastic.cob"
  cob_nop ();
#line 659 "stochastic.c"

  /* Line: 134       : WHEN               : stochastic.cob */
#line 134 "stochastic.cob"
  cob_nop ();
#line 664 "stochastic.c"

  if (((int)memcmp (b_24, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 135       : MOVE               : stochastic.cob */
#line 135 "stochastic.cob"
    cob_nop ();
#line 672 "stochastic.c"
    cob_move ((cob_field *)&c_16, &f_47);
    goto l_10;
  }

  /* Line: 136       : WHEN               : stochastic.cob */
#line 136 "stochastic.cob"
  cob_nop ();
#line 680 "stochastic.c"

  if (((int)memcmp (b_24, (cob_u8_ptr)"39", 2) == 0))
  {

    /* Line: 137       : MOVE               : stochastic.cob */
#line 137 "stochastic.cob"
    cob_nop ();
#line 688 "stochastic.c"
    cob_move ((cob_field *)&c_17, &f_47);
    goto l_10;
  }

  /* WHEN OTHER */

  /* Line: 139       : STRING             : stochastic.cob */
#line 139 "stochastic.cob"
  cob_nop ();
#line 698 "stochastic.c"
  cob_string_init (&f_47, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_24);
  cob_string_finish ();

  /* End EVALUATE */
  l_10:;

  /* Line: 142       : DISPLAY            : stochastic.cob */
#line 142 "stochastic.cob"
  cob_nop ();
#line 711 "stochastic.c"
  cob_display (0, 1, 1, &f_47);

  /* Line: 143       : MOVE               : stochastic.cob */
#line 143 "stochastic.cob"
  cob_nop ();
#line 717 "stochastic.c"
  cob_move ((cob_field *)&c_1, &f_46);

  /* Line: 144       : CLOSE              : stochastic.cob */
#line 144 "stochastic.cob"
  cob_nop ();
#line 723 "stochastic.c"
  cob_close (h_FD_PRICES_FILE, &f_24, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_1;
    l_20:
    frame_ptr--;
  }

  /* Line: 145       : EXIT               : stochastic.cob */
#line 145 "stochastic.cob"
  cob_nop ();
#line 741 "stochastic.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : stochastic.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  STOCHASTIC_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-PRICE-IDX */
#line 26 "stochastic.cob"
  cob_nop ();
#line 812 "stochastic.c"
  b_30 = 1;

  /* initialize field WS-PRICES-STATUS */
#line 20 "stochastic.cob"
  cob_nop ();
#line 818 "stochastic.c"
  memset (b_24, (unsigned char)' ', 2);

  /* initialize field WS-PRICES-PATH */
#line 23 "stochastic.cob"
  cob_nop ();
#line 824 "stochastic.c"
  memset (b_27, (unsigned char)' ', 200);

  /* initialize WS-PRICE-ENTRY: init first record */
  {
    /* initialize field WS-HIGH-COMP3 */
#line 27 "stochastic.cob"
    cob_nop ();
#line 832 "stochastic.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28, &a_7));
    /* initialize field WS-LOW-COMP3 */
#line 28 "stochastic.cob"
    cob_nop ();
#line 837 "stochastic.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28 + 4, &a_7));
    /* initialize field WS-CLOSE-COMP3 */
#line 29 "stochastic.cob"
    cob_nop ();
#line 842 "stochastic.c"
    cob_set_packed_zero (COB_SET_FLD (f0, 4, b_28 + 8, &a_7));
    /* initialize WS-PRICE-ENTRY: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_28;
      memcpy (b_ptr +     12, b_ptr,     12);	/* WS-PRICE-ENTRY:     2 thru 2 */
      memcpy (b_ptr +     24, b_ptr,     24);	/* WS-PRICE-ENTRY:     3 thru 4 */
      memcpy (b_ptr +     48, b_ptr,     48);	/* WS-PRICE-ENTRY:     5 thru 8 */
      memcpy (b_ptr +     96, b_ptr,     96);	/* WS-PRICE-ENTRY:     9 thru 16 */
      memcpy (b_ptr +    192, b_ptr,    192);	/* WS-PRICE-ENTRY:    17 thru 32 */
      memcpy (b_ptr +    384, b_ptr,    384);	/* WS-PRICE-ENTRY:    33 thru 64 */
      memcpy (b_ptr +    768, b_ptr,    768);	/* WS-PRICE-ENTRY:    65 thru 128 */
      memcpy (b_ptr +   1536, b_ptr,   1536);	/* WS-PRICE-ENTRY:   129 thru 256 */
      memcpy (b_ptr +   3072, b_ptr,   3072);	/* WS-PRICE-ENTRY:   257 thru 512 */
      memcpy (b_ptr +   6144, b_ptr,   5856);	/* WS-PRICE-ENTRY:   513 thru 1000 */
    }
  }

  /* initialize field WS-COUNT */
#line 30 "stochastic.cob"
  cob_nop ();
#line 863 "stochastic.c"
  cob_move ((cob_field *)&c_11, &f_34);

  /* initialize field WS-I */
#line 31 "stochastic.cob"
  cob_nop ();
#line 869 "stochastic.c"
  memset (b_35, 0x0, 2);

  /* initialize field WS-J */
#line 32 "stochastic.cob"
  cob_nop ();
#line 875 "stochastic.c"
  memset (b_36, 0x0, 2);

  /* initialize field WS-K-PERIOD */
#line 33 "stochastic.cob"
  cob_nop ();
#line 881 "stochastic.c"
  cob_move ((cob_field *)&c_19, &f_37);

  /* initialize field WS-D-PERIOD */
#line 34 "stochastic.cob"
  cob_nop ();
#line 887 "stochastic.c"
  cob_move ((cob_field *)&c_20, &f_38);

  /* initialize field WS-HIGHEST */
#line 35 "stochastic.cob"
  cob_nop ();
#line 893 "stochastic.c"
  cob_set_packed_zero (&f_39);

  /* initialize field WS-LOWEST */
#line 36 "stochastic.cob"
  cob_nop ();
#line 899 "stochastic.c"
  cob_set_packed_zero (&f_40);

  /* initialize field WS-PCT-K */
#line 37 "stochastic.cob"
  cob_nop ();
#line 905 "stochastic.c"
  memset (b_41, (unsigned char)'0', 5);

  /* initialize field WS-PCT-D */
#line 38 "stochastic.cob"
  cob_nop ();
#line 911 "stochastic.c"
  memset (b_42, (unsigned char)'0', 5);

  /* initialize field WS-SUM-D */
#line 39 "stochastic.cob"
  cob_nop ();
#line 917 "stochastic.c"
  cob_set_packed_zero (&f_43);

  /* initialize field WS-START-IDX */
#line 40 "stochastic.cob"
  cob_nop ();
#line 923 "stochastic.c"
  memset (b_44, 0x0, 2);

  /* initialize field WS-START-D */
#line 41 "stochastic.cob"
  cob_nop ();
#line 929 "stochastic.c"
  memset (b_45, 0x0, 2);

  /* initialize field WS-EXIT-CODE */
#line 42 "stochastic.cob"
  cob_nop ();
#line 935 "stochastic.c"
  cob_move ((cob_field *)&c_11, &f_46);

  /* initialize field WS-ERROR-MSG */
#line 43 "stochastic.cob"
  cob_nop ();
#line 941 "stochastic.c"
  memset (b_47, (unsigned char)' ', 100);


  /* File initialization for FD-PRICES-FILE */
  cob_file_malloc (&h_FD_PRICES_FILE, NULL, 0, 0);
  h_FD_PRICES_FILE->select_name = (const char *)"FD-PRICES-FILE";
  h_FD_PRICES_FILE->file_status = h_FD_PRICES_FILE_status;
  memset (h_FD_PRICES_FILE_status, '0', 2);
  h_FD_PRICES_FILE->assign = &f_27;
  h_FD_PRICES_FILE->record = &f_23;
  h_FD_PRICES_FILE->variable_record = NULL;
  h_FD_PRICES_FILE->record_min = 0;
  h_FD_PRICES_FILE->record_max = 32;
  h_FD_PRICES_FILE->file = NULL;
  h_FD_PRICES_FILE->organization = 1;
  h_FD_PRICES_FILE->access_mode = 1;
  h_FD_PRICES_FILE->lock_mode = 0;
  h_FD_PRICES_FILE->open_mode = 0;
  h_FD_PRICES_FILE->flag_optional = 0;
  h_FD_PRICES_FILE->flag_line_adv = 0;
  h_FD_PRICES_FILE->flag_select_features = 1;

  /* Set Decimal Constant values */
  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'STOCHASTIC' */

/* Initialize module structure for STOCHASTIC */
static void STOCHASTIC_module_init (cob_module *module)
{
  module->module_name = "STOCHASTIC";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())STOCHASTIC;
  module->module_cancel.funcptr = (void *(*)())STOCHASTIC_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

