/* Generated by           cobc 3.2.0 */
/* Generated from         stochastic.cob */
/* Generated at           abr 25 2026 18:21:36 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g -o stochastic stochastic.cob */

/* Program local variables for 'STOCHASTIC' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;
cob_decimal	*d_2 = NULL;


/* File FD-PRICES-FILE */
static cob_file		*h_FD_PRICES_FILE = NULL;
static unsigned char	h_FD_PRICES_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_23[32] __attribute__((aligned));	/* FD-PRICES-FILE Record */
static cob_u8_t	b_24[2] __attribute__((aligned));	/* WS-PRICES-STATUS */
static cob_u8_t	b_27[200] __attribute__((aligned));	/* WS-PRICES-PATH */
static cob_u8_t	b_28[12000] __attribute__((aligned));	/* WS-PRICES-TABLE */
static int	b_30;	/* WS-PRICE-IDX */
static cob_u8_t	b_34[2] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_35[2] __attribute__((aligned));	/* WS-I */
static cob_u8_t	b_36[2] __attribute__((aligned));	/* WS-J */
static cob_u8_t	b_37[1] __attribute__((aligned));	/* WS-K-PERIOD */
static cob_u8_t	b_38[1] __attribute__((aligned));	/* WS-D-PERIOD */
static cob_u8_t	b_39[4] __attribute__((aligned));	/* WS-HIGHEST */
static cob_u8_t	b_40[4] __attribute__((aligned));	/* WS-LOWEST */
static cob_u8_t	b_41[5] __attribute__((aligned));	/* WS-PCT-K */
static cob_u8_t	b_42[5] __attribute__((aligned));	/* WS-PCT-D */
static cob_u8_t	b_43[4] __attribute__((aligned));	/* WS-SUM-D */
static cob_u8_t	b_44[2] __attribute__((aligned));	/* WS-START-IDX */
static cob_u8_t	b_45[2] __attribute__((aligned));	/* WS-START-D */
static cob_u8_t	b_46[2] __attribute__((aligned));	/* WS-EXIT-CODE */
static cob_u8_t	b_47[100] __attribute__((aligned));	/* WS-ERROR-MSG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {10, b_23, &a_4};	/* FD-PRICE-HIGH-RAW */
static cob_field f_20	= {10, b_23 + 11, &a_4};	/* FD-PRICE-LOW-RAW */
static cob_field f_22	= {10, b_23 + 22, &a_4};	/* FD-PRICE-CLOSE-RAW */
static cob_field f_23	= {32, b_23, &a_4};	/* FD-PRICES-FILE Record */
static cob_field f_24	= {2, b_24, &a_4};	/* WS-PRICES-STATUS */
static cob_field f_27	= {200, b_27, &a_4};	/* WS-PRICES-PATH */
static cob_field f_34	= {2, b_34, &a_6};	/* WS-COUNT */
static cob_field f_35	= {2, b_35, &a_6};	/* WS-I */
static cob_field f_37	= {1, b_37, &a_8};	/* WS-K-PERIOD */
static cob_field f_38	= {1, b_38, &a_8};	/* WS-D-PERIOD */
static cob_field f_39	= {4, b_39, &a_7};	/* WS-HIGHEST */
static cob_field f_40	= {4, b_40, &a_7};	/* WS-LOWEST */
static cob_field f_41	= {5, b_41, &a_9};	/* WS-PCT-K */
static cob_field f_42	= {5, b_42, &a_9};	/* WS-PCT-D */
static cob_field f_43	= {4, b_43, &a_7};	/* WS-SUM-D */
static cob_field f_44	= {2, b_44, &a_6};	/* WS-START-IDX */
static cob_field f_45	= {2, b_45, &a_6};	/* WS-START-D */
static cob_field f_46	= {2, b_46, &a_5};	/* WS-EXIT-CODE */
static cob_field f_47	= {100, b_47, &a_4};	/* WS-ERROR-MSG */

/* End of fields */

